CREATE TABLE zeitausgleich
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personalnummer      INTEGER references personalnummer(id),
    datum               date,
    time_von            time,
    time_bis            time,
    created_on          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by          VARCHAR(255),
    changed_on          TIMESTAMP WITHOUT TIME ZONE,
    changed_by          VARCHAR(255)
);

CREATE TABLE zeitausgleich_history
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zeitausgleich_id    INTEGER,
    personalnummer      INTEGER,
    datum               date,
    time_von            time,
    time_bis            time,
    created_on          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by          VARCHAR(255),
    changed_on          TIMESTAMP WITHOUT TIME ZONE,
    changed_by          VARCHAR(255),
    action              CHAR,
    action_timestamp    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE OR REPLACE FUNCTION zeitausgleich_audit() RETURNS TRIGGER
LANGUAGE plpgsql
AS
$$
BEGIN
    IF TG_OP = 'DELETE' THEN
        INSERT INTO zeitausgleich_history (
            zeitausgleich_id, personalnummer, datum, time_von, time_bis,
            created_on, created_by, changed_on, changed_by, action, action_timestamp
        )
        VALUES (
            OLD.id, OLD.personalnummer, OLD.datum, OLD.time_von, OLD.time_bis,
            OLD.created_on, OLD.created_by, OLD.changed_on, OLD.changed_by, 'D', NOW()
        );
        RETURN OLD;
    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO zeitausgleich_history (
            zeitausgleich_id, personalnummer, datum, time_von, time_bis,
            created_on, created_by, changed_on, changed_by, action, action_timestamp
        )
        VALUES (
            NEW.id, NEW.personalnummer, NEW.datum, NEW.time_von, NEW.time_bis,
            NEW.created_on, NEW.created_by, NEW.changed_on, NEW.changed_by, 'U', NOW()
        );
        RETURN NEW;
    ELSIF TG_OP = 'INSERT' THEN
        INSERT INTO zeitausgleich_history (
            zeitausgleich_id, personalnummer, datum, time_von, time_bis,
            created_on, created_by, changed_on, changed_by, action, action_timestamp
        )
        VALUES (
            NEW.id, NEW.personalnummer, NEW.datum, NEW.time_von, NEW.time_bis,
            NEW.created_on, NEW.created_by, NEW.changed_on, NEW.changed_by, 'I', NOW()
        );
        RETURN NEW;
    END IF;
    RETURN NULL; -- result is ignored since this is an AFTER trigger
END;
$$;

alter function zeitausgleich_audit() owner to ibosng;

CREATE TRIGGER zeitausgleich_insert
    AFTER INSERT
    ON zeitausgleich
    FOR EACH ROW
EXECUTE FUNCTION zeitausgleich_audit();

CREATE TRIGGER zeitausgleich_update
    AFTER UPDATE
    ON zeitausgleich
    FOR EACH ROW
EXECUTE FUNCTION zeitausgleich_audit();

CREATE TRIGGER zeitausgleich_delete
    AFTER DELETE
    ON zeitausgleich
    FOR EACH ROW
EXECUTE FUNCTION zeitausgleich_audit();
