CREATE TABLE anspruch (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lhr_id INT NOT NULL,
    bezeichnung VARCHAR(255) NOT NULL,
    created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    changed_on TIMESTAMP,
    changed_by VARCHAR(255)
);

CREATE TABLE anspruch_history
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anspruch_id       INTEGER,
    lhr_id            INT,
    bezeichnung       VARCHAR(255),
    created_on        TIMESTAMP,
    created_by        VARCHAR(255),
    changed_on        TIMESTAMP,
    changed_by        VARCHAR(255),
    action            CHAR,
    action_timestamp  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE OR REPLACE FUNCTION anspruch_audit() RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        INSERT INTO anspruch_history (anspruch_id, lhr_id, bezeichnung, created_on, created_by, changed_on, changed_by, action, action_timestamp)
        VALUES (OLD.id, OLD.lhr_id, OLD.bezeichnung, OLD.created_on, OLD.created_by, OLD.changed_on, OLD.changed_by, 'D', NOW());
        RETURN OLD;
    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO anspruch_history (anspruch_id, lhr_id, bezeichnung, created_on, created_by, changed_on, changed_by, action, action_timestamp)
        VALUES (NEW.id, NEW.lhr_id, NEW.bezeichnung, NEW.created_on, NEW.created_by, NEW.changed_on, NEW.changed_by, 'U', NOW());
        RETURN NEW;
    ELSIF TG_OP = 'INSERT' THEN
        INSERT INTO anspruch_history (anspruch_id, lhr_id, bezeichnung, created_on, created_by, changed_on, changed_by, action, action_timestamp)
        VALUES (NEW.id, NEW.lhr_id, NEW.bezeichnung, NEW.created_on, NEW.created_by, NEW.changed_on, NEW.changed_by, 'I', NOW());
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$;

ALTER FUNCTION anspruch_audit() OWNER TO ibosng;

CREATE TRIGGER anspruch_insert
AFTER INSERT ON anspruch
FOR EACH ROW
EXECUTE FUNCTION anspruch_audit();

CREATE TRIGGER anspruch_update
AFTER UPDATE ON anspruch
FOR EACH ROW
EXECUTE FUNCTION anspruch_audit();

CREATE TRIGGER anspruch_delete
AFTER DELETE ON anspruch
FOR EACH ROW
EXECUTE FUNCTION anspruch_audit();

INSERT INTO anspruch(lhr_id, bezeichnung) VALUES
(1, 'Normalurlaub'),
(2, 'Pflegeurlaub 1 Woche'),
(3, 'Pflegeurlaub 2 Woche');

