CREATE TABLE abmeldung
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    personalnummer  INTEGER,
    austritts_datum date,
    austrittsgrund  VARCHAR(255),
    bemerkung       VARCHAR(255),
    created_on      TIMESTAMP DEFAULT CURRENT_TIMESTAMP      NOT NULL,
    created_by      VARCHAR(255),
    changed_on      TIMESTAMP WITHOUT TIME ZONE,
    changed_by      VARCHAR(255),
    CONSTRAINT pk_abmeldung PRIMARY KEY (id)
);

CREATE TABLE abmeldung_history
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    abmeldung_id     INTEGER                                  NOT NULL,
    personalnummer   INTEGER,
    austritts_datum  date,
    austrittsgrund   VARCHAR(255),
    bemerkung        VARCHAR(255),
    created_on       TIMESTAMP DEFAULT CURRENT_TIMESTAMP      NOT NULL,
    created_by       VARCHAR(255),
    changed_on       TIMESTAMP WITHOUT TIME ZONE,
    changed_by       VARCHAR(255),
    action           CHAR,
    action_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP      NOT NULL
);

CREATE
OR REPLACE FUNCTION abmeldung_audit() RETURNS TRIGGER
    LANGUAGE plpgsql
AS
$$
BEGIN
    IF
TG_OP = 'DELETE' THEN
        INSERT INTO abmeldung_history (abmeldung_id, personalnummer, austritts_datum, austrittsgrund, bemerkung, created_on, created_by, changed_on,
                                       changed_by, action, action_timestamp)
        VALUES (OLD.id, OLD.personalnummer, OLD.austritts_datum, OLD.austrittsgrund, OLD.bemerkung, OLD.created_on, OLD.created_by,
                OLD.changed_on, OLD.changed_by, 'D', NOW());
RETURN OLD;
ELSIF
TG_OP = 'UPDATE' THEN
        INSERT INTO abmeldung_history (abmeldung_id, personalnummer, austritts_datum, austrittsgrund, bemerkung, created_on, created_by,
                                       changed_on, changed_by, action, action_timestamp)
        VALUES (NEW.id, NEW.personalnummer, NEW.austritts_datum, NEW.austrittsgrund, NEW.bemerkung, NEW.created_on, NEW.created_by,
                NEW.changed_on, NEW.changed_by, 'U', NOW());
RETURN NEW;
ELSIF
TG_OP = 'INSERT' THEN
        INSERT INTO abmeldung_history (abmeldung_id, personalnummer, austritts_datum, austrittsgrund, bemerkung, created_on, created_by,
                                       changed_on,
                                       changed_by, action, action_timestamp)
        VALUES (NEW.id, NEW.personalnummer, NEW.austritts_datum, NEW.austrittsgrund, NEW.bemerkung, NEW.created_on, NEW.created_by,
                NEW.changed_on, NEW.changed_by, 'I', NOW());
RETURN NEW;
END IF;
RETURN NULL; -- result is ignored since this is an AFTER trigger
END;
$$;

alter function abmeldung_audit() owner to ibosng;

CREATE TRIGGER abmeldung_insert
    AFTER INSERT
    ON abmeldung
    FOR EACH ROW
    EXECUTE FUNCTION abmeldung_audit();

CREATE TRIGGER abmeldung_update
    AFTER UPDATE
    ON abmeldung
    FOR EACH ROW
    EXECUTE FUNCTION abmeldung_audit();

CREATE TRIGGER abmeldung_delete
    AFTER DELETE
    ON abmeldung
    FOR EACH ROW
    EXECUTE FUNCTION abmeldung_audit();

