CREATE TABLE austrittsgrund
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lhr_grund        VARCHAR(255),
    beschreibung VARCHAR(255),
    created_on   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by   VARCHAR(255),
    changed_on   TIMESTAMP WITHOUT TIME ZONE,
    changed_by   VARCHAR(255)
);

CREATE TABLE austrittsgrund_history
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    austrittsgrund_id INTEGER                             NOT NULL,
    lhr_grund             VARCHAR(255),
    beschreibung      VARCHAR(255),
    created_on        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by        VARCHAR(255),
    changed_on        TIMESTAMP WITHOUT TIME ZONE,
    changed_by        VARCHAR(255),
    action            CHAR,
    action_timestamp  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE
OR REPLACE FUNCTION austrittsgrund_audit() RETURNS TRIGGER
    LANGUAGE plpgsql
AS
$$
BEGIN
    IF
TG_OP = 'DELETE' THEN
        INSERT INTO austrittsgrund_history (austrittsgrund_id, lhr_grund, beschreibung, created_on, created_by , changed_on, changed_by, action, action_timestamp)
        VALUES (OLD.id, OLD.lhr_grund, OLD.beschreibung, OLD.created_on, OLD.created_by, OLD.changed_on, OLD.changed_by, 'D', NOW());
RETURN OLD;
ELSIF
TG_OP = 'UPDATE' THEN
        INSERT INTO austrittsgrund_history (austrittsgrund_id, lhr_grund, beschreibung, created_on, created_by , changed_on, changed_by, action, action_timestamp)
        VALUES (NEW.id, NEW.lhr_grund, NEW.beschreibung, NEW.created_on, NEW.created_by , NEW.changed_on, NEW.changed_by, 'U', NOW());
RETURN NEW;
ELSIF
TG_OP = 'INSERT' THEN
        INSERT INTO austrittsgrund_history (austrittsgrund_id, lhr_grund, beschreibung, created_on, created_by , changed_on, changed_by, action, action_timestamp)
        VALUES (NEW.id, NEW.lhr_grund, NEW.beschreibung, NEW.created_on, NEW.created_by , NEW.changed_on, NEW.changed_by, 'I', NOW());
RETURN NEW;
END IF;
RETURN NULL; -- result is ignored since this is an AFTER trigger
END;
$$;

alter function austrittsgrund_audit() owner to ibosng;

CREATE TRIGGER austrittsgrund_insert
    AFTER INSERT
    ON austrittsgrund
    FOR EACH ROW
    EXECUTE FUNCTION austrittsgrund_audit();

CREATE TRIGGER austrittsgrund_update
    AFTER UPDATE
    ON austrittsgrund
    FOR EACH ROW
    EXECUTE FUNCTION austrittsgrund_audit();

CREATE TRIGGER austrittsgrund_delete
    AFTER DELETE
    ON austrittsgrund
    FOR EACH ROW
    EXECUTE FUNCTION austrittsgrund_audit();



INSERT INTO austrittsgrund(lhr_grund, beschreibung, created_by)
VALUES ('AFL1', '§ 14/1: Lehrvertrag endet ohne absolvierte LAP', current_user),
       ('AFL2', '§ 14/2 (a): Lehrvertrag endet bei Tod des Lehrlings', current_user),
       ('AFL3', '§ 14/2 (e): Lehrvertrag endet bei positiver LAP', current_user),
       ('AFL4', '§ 15a/1 (TN): Probezeitlösung durch den Lehrling', current_user),
       ('AFL5', '§ 15a/1 (DG): Probezeitlösung durch den Dienstgeber', current_user),
       ('AFL6', '§ 15a/3 (a): Kündigung durch DG – strafbare Handlungen des Lehrlings', current_user),
       ('AFL7', '§ 15a/3 (b): Kündigung durch DG – gefährliche Drohung oder Gesetzesverstöße', current_user),
       ('AFL8', '§ 15a/3 (c): Kündigung durch DG – Pflichtverletzung des Lehrlings', current_user),
       ('AFL9', '§ 15a/3 (d): Kündigung durch DG – Verrat von Geschäftsgeheimnissen', current_user),
       ('AFL10', '§ 15a/3 (e): Kündigung durch DG – unerlaubtes Verlassen des Lehrplatzes', current_user),
       ('AFL11', '§ 15a/3 (f): Kündigung durch DG – Berufsunfähigkeit des Lehrlings', current_user),
       ('AFL12', '§ 15a/4 (a): Kündigung durch Lehrling – gesundheitliche Gründe', current_user),
       ('AFL13', '§ 15a/4 (b): Kündigung durch Lehrling – Pflichtverletzung oder Gesetzesverstöße des DG',
        current_user),
       ('AFL14', '§ 15a/4 (g): Kündigung durch Lehrling – Aufgabe des Lehrberufs', current_user),
       ('AFL15', '§ 15a/5: Einvernehmliche Auflösung', current_user);