create table beruf
(
    id         integer generated by default as identity primary key,
    name       text                                not null,
    created_on timestamp default CURRENT_TIMESTAMP not null,
    created_by text      default CURRENT_USER      not null,
    changed_on timestamp,
    changed_by text,
    status     smallint  default 1                 not null
);

CREATE TABLE beruf_history
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    beruf_id         INTEGER                             NOT NULL,
    name             TEXT                                NOT NULL,
    created_on       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by       TEXT      DEFAULT CURRENT_USER      NOT NULL,
    changed_on       TIMESTAMP,
    changed_by       TEXT,
    status           smallint                            NOT NULL DEFAULT 1,
    action           CHAR,
    action_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE
    OR REPLACE FUNCTION beruf_audit() RETURNS TRIGGER
    LANGUAGE plpgsql
AS
$$
BEGIN
    IF
        TG_OP = 'DELETE' THEN
        INSERT INTO beruf_history (beruf_id, name, created_on, created_by, changed_on,
                                   changed_by, status,
                                   action, action_timestamp)
        VALUES (OLD.id,
                OLD.name,
                OLD.created_on,
                OLD.created_by,
                OLD.changed_on,
                OLD.changed_by,
                OLD.status,
                'D', NOW());
        RETURN OLD;
    ELSIF
        TG_OP = 'UPDATE' THEN
        INSERT INTO beruf_history (beruf_id, name, created_on, created_by, changed_on,
                                   changed_by, status,
                                   action, action_timestamp)
        VALUES (NEW.id,
                NEW.name,
                NEW.created_on,
                NEW.created_by,
                NEW.changed_on,
                NEW.changed_by,
                NEW.status, 'U', NOW());
        RETURN NEW;
    ELSIF
        TG_OP = 'INSERT' THEN
        INSERT INTO beruf_history (beruf_id, name, created_on, created_by, changed_on,
                                   changed_by, status,
                                   action, action_timestamp)
        VALUES (NEW.id,
                NEW.name,
                NEW.created_on,
                NEW.created_by,
                NEW.changed_on,
                NEW.changed_by,
                NEW.status, 'I', NOW());

        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$;

ALTER FUNCTION beruf_audit() OWNER TO ibosng;

CREATE TRIGGER beruf_insert
    AFTER INSERT
    ON beruf
    FOR EACH ROW
EXECUTE PROCEDURE beruf_audit();

CREATE TRIGGER beruf_update
    AFTER UPDATE
    ON beruf
    FOR EACH ROW
EXECUTE PROCEDURE beruf_audit();

CREATE TRIGGER beruf_delete
    AFTER DELETE
    ON beruf
    FOR EACH ROW
EXECUTE PROCEDURE beruf_audit();

create table teilnehmer_2_wunschberuf
(
    id             integer generated always as identity primary key,
    teilnehmer_id  integer                             not null references teilnehmer (id),
    wunschberuf_id integer                             not null references beruf (id),
    created_on     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by     text      default CURRENT_USER      not null,
    changed_on     timestamp,
    changed_by     text
);

CREATE TABLE teilnehmer_2_wunschberuf_history
(
    id                          integer generated always as identity primary key,
    teilnehmer_2_wunschberuf_id integer                             not null,
    teilnehmer_id               integer                             not null,
    wunschberuf_id              integer                             not null,
    created_on                  timestamp,
    action                      char                                not null,
    action_timestamp            timestamp default CURRENT_TIMESTAMP not null,
    created_by                  text      default CURRENT_USER      not null,
    changed_on                  timestamp,
    changed_by                  text
);

CREATE OR REPLACE FUNCTION teilnehmer_2_wunschberuf_audit() RETURNS TRIGGER
    LANGUAGE plpgsql
AS
$$
BEGIN
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO teilnehmer_2_wunschberuf_history (teilnehmer_2_wunschberuf_id, teilnehmer_id, wunschberuf_id,
                                                      created_on,
                                                      action, action_timestamp, created_by, changed_on, changed_by)
        VALUES (OLD.id, OLD.teilnehmer_id, OLD.wunschberuf_id, OLD.created_on, 'D', now(), OLD.created_by,
                OLD.changed_on, OLD.changed_by);
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO teilnehmer_2_wunschberuf_history (teilnehmer_2_wunschberuf_id, teilnehmer_id, wunschberuf_id,
                                                      created_on,
                                                      action, action_timestamp, created_by, changed_on, changed_by)
        VALUES (NEW.id, NEW.teilnehmer_id, NEW.wunschberuf_id, NEW.created_on, 'U', now(), NEW.created_by,
                NEW.changed_on, NEW.changed_by);
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO teilnehmer_2_wunschberuf_history (teilnehmer_2_wunschberuf_id, teilnehmer_id, wunschberuf_id,
                                                      created_on,
                                                      action, action_timestamp, created_by, changed_on, changed_by)
        VALUES (NEW.id, NEW.teilnehmer_id, NEW.wunschberuf_id, NEW.created_on, 'I', now(), NEW.created_by,
                NEW.changed_on, NEW.changed_by);
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$;

alter function teilnehmer_2_wunschberuf_audit() owner to ibosng;

create trigger teilnehmer_2_wunschberuf_insert
    after insert
    on teilnehmer_2_wunschberuf
    for each row
execute procedure teilnehmer_2_wunschberuf_audit();

create trigger teilnehmer_2_wunschberuf_update
    after update
    on teilnehmer_2_wunschberuf
    for each row
execute procedure teilnehmer_2_wunschberuf_audit();

create trigger teilnehmer_2_wunschberuf_delete
    after delete
    on teilnehmer_2_wunschberuf
    for each row
execute procedure teilnehmer_2_wunschberuf_audit();


CREATE TABLE tn_berufserfahrung
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teilnehmer INTEGER                             NOT NULL REFERENCES teilnehmer (id),
    beruf      integer                             not null references beruf (id),
    dauer      INTEGER,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by TEXT      DEFAULT CURRENT_USER      NOT NULL,
    changed_on TIMESTAMP,
    changed_by TEXT
);

CREATE TABLE tn_berufserfahrung_history
(
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tn_berufserfahrung_id INTEGER                             NOT NULL,
    teilnehmer            INTEGER                             NOT NULL,
    beruf                 INTEGER                             NOT NULL,
    dauer                 INTEGER,
    created_on            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by            TEXT      DEFAULT CURRENT_USER      NOT NULL,
    changed_on            TIMESTAMP,
    changed_by            TEXT,
    action                CHAR,
    action_timestamp      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE
    OR REPLACE FUNCTION tn_berufserfahrung_audit() RETURNS TRIGGER
    LANGUAGE plpgsql
AS
$$
BEGIN
    IF
        TG_OP = 'DELETE' THEN
        INSERT INTO tn_berufserfahrung_history (tn_berufserfahrung_id, teilnehmer, beruf, dauer, created_on, created_by,
                                                changed_on,
                                                changed_by,
                                                action, action_timestamp)
        VALUES (OLD.id,
                OLD.teilnehmer,
                OLD.beruf,
                OLD.dauer,
                OLD.created_on,
                OLD.created_by,
                OLD.changed_on,
                OLD.changed_by,
                'D', NOW());
        RETURN OLD;
    ELSIF
        TG_OP = 'UPDATE' THEN
        INSERT INTO tn_berufserfahrung_history (tn_berufserfahrung_id, teilnehmer, beruf, dauer, created_on, created_by,
                                                changed_on,
                                                changed_by,
                                                action, action_timestamp)
        VALUES (NEW.id,
                NEW.teilnehmer,
                NEW.beruf,
                NEW.dauer,
                NEW.created_on,
                NEW.created_by,
                NEW.changed_on,
                NEW.changed_by, 'U', NOW());
        RETURN NEW;
    ELSIF
        TG_OP = 'INSERT' THEN
        INSERT INTO tn_berufserfahrung_history (tn_berufserfahrung_id, teilnehmer, beruf, dauer, created_on, created_by,
                                                changed_on,
                                                changed_by,
                                                action, action_timestamp)
        VALUES (NEW.id,
                NEW.teilnehmer,
                NEW.beruf,
                NEW.dauer,
                NEW.created_on,
                NEW.created_by,
                NEW.changed_on,
                NEW.changed_by, 'I', NOW());

        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$;

ALTER FUNCTION tn_berufserfahrung_audit() OWNER TO ibosng;

CREATE TRIGGER tn_berufserfahrung_insert
    AFTER INSERT
    ON tn_berufserfahrung
    FOR EACH ROW
EXECUTE PROCEDURE tn_berufserfahrung_audit();

CREATE TRIGGER tn_berufserfahrung_update
    AFTER UPDATE
    ON tn_berufserfahrung
    FOR EACH ROW
EXECUTE PROCEDURE tn_berufserfahrung_audit();

CREATE TRIGGER tn_berufserfahrung_delete
    AFTER DELETE
    ON tn_berufserfahrung
    FOR EACH ROW
EXECUTE PROCEDURE tn_berufserfahrung_audit();
