INSERT INTO seminar_pruefung_bezeichnung (name)
VALUES ('Wiederholungsprüfung'),
       ('Lehrabschluss'),
       ('Teilqualifizierungsabschluss'),
       ('Berufsschulzeugnis'),
       ('Pflichtschulabschlussprüfung'),
       ('Ausbildungsabschluss');


INSERT INTO seminar_pruefung_art (name)
VALUES ('Praxisarbeit'),
       ('Kombi (mündlich & schriftlich)');


INSERT INTO seminar_pruefung_gegenstand (name)
VALUES ('Gesundheit & Soziales'),
       ('Natur & Technik'),
       ('Berufsorientierung'),
       ('Fit4Internet'),
       ('Finanzführerschein'),
       ('Werte & Orientierung'),
       ('AHS-Matura'),
       ('Studium'),
       ('HTL-Matura'),
       ('Colleg'),
       ('Fachschule'),
       ('Fachhochschule'),
       ('Lohnverrechnungsausbildung'),
       ('Berufsschulzeugnis');

DELETE
FROM seminar_pruefung_niveau
WHERE name IN ('C1', 'C2');

DELETE
FROM seminar_pruefung_institut
WHERE name = 'intern';

INSERT INTO seminar_pruefung_institut (name)
VALUES ('WKO'),
       ('LK'),
       ('Colleg'),
       ('Schule'),
       ('Universität'),
       ('FH');


CREATE TABLE seminar_pruefung_begruendung
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT                                NOT NULL,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by TEXT      DEFAULT CURRENT_USER      NOT NULL,
    changed_on TIMESTAMP,
    changed_by TEXT,
    status     smallint                            NOT NULL DEFAULT 1
);

CREATE TABLE seminar_pruefung_begruendung_history
(
    id                              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seminar_pruefung_begruendung_id INTEGER                             NOT NULL,
    name                            TEXT                                NOT NULL,
    created_on                      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by                      TEXT      DEFAULT CURRENT_USER      NOT NULL,
    changed_on                      TIMESTAMP,
    changed_by                      TEXT,
    status                          smallint                            NOT NULL DEFAULT 1,
    action                          CHAR,
    action_timestamp                TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE
    OR REPLACE FUNCTION seminar_pruefung_begruendung_audit() RETURNS TRIGGER
    LANGUAGE plpgsql
AS
$$
BEGIN
    IF
        TG_OP = 'DELETE' THEN
        INSERT INTO seminar_pruefung_begruendung_history (seminar_pruefung_begruendung_id, name, created_on,
                                                          created_by, changed_on, changed_by, status,
                                                          action, action_timestamp)
        VALUES (OLD.id,
                OLD.name,
                OLD.created_on,
                OLD.created_by,
                OLD.changed_on,
                OLD.changed_by,
                OLD.status,
                'D', NOW());
        RETURN OLD;
    ELSIF
        TG_OP = 'UPDATE' THEN
        INSERT INTO seminar_pruefung_begruendung_history (seminar_pruefung_begruendung_id, name, created_on,
                                                          created_by, changed_on, changed_by, status,
                                                          action, action_timestamp)
        VALUES (NEW.id,
                NEW.name,
                NEW.created_on,
                NEW.created_by,
                NEW.changed_on,
                NEW.changed_by,
                NEW.status, 'U', NOW());
        RETURN NEW;
    ELSIF
        TG_OP = 'INSERT' THEN
        INSERT INTO seminar_pruefung_begruendung_history (seminar_pruefung_begruendung_id, name, created_on,
                                                          created_by, changed_on, changed_by, status,
                                                          action, action_timestamp)
        VALUES (NEW.id,
                NEW.name,
                NEW.created_on,
                NEW.created_by,
                NEW.changed_on,
                NEW.changed_by,
                NEW.status, 'I', NOW());
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$;

ALTER FUNCTION seminar_pruefung_begruendung_audit() OWNER TO ibosng;

CREATE TRIGGER seminar_pruefung_begruendung_insert
    AFTER INSERT
    ON seminar_pruefung_begruendung
    FOR EACH ROW
EXECUTE PROCEDURE seminar_pruefung_begruendung_audit();

CREATE TRIGGER seminar_pruefung_begruendung_update
    AFTER UPDATE
    ON seminar_pruefung_begruendung
    FOR EACH ROW
EXECUTE PROCEDURE seminar_pruefung_begruendung_audit();

CREATE TRIGGER seminar_pruefung_begruendung_delete
    AFTER DELETE
    ON seminar_pruefung_begruendung
    FOR EACH ROW
EXECUTE PROCEDURE seminar_pruefung_begruendung_audit();

INSERT INTO seminar_pruefung_begruendung(name)
VALUES ('Anwesenheit zu gering'),
       ('zu geringer Lernfortschritt'),
       ('Sonstiges');



DROP TABLE seminar_pruefung_ergebnis;
DROP TABLE seminar_pruefung_ergebnis_history;
DROP FUNCTION IF EXISTS seminar_pruefung_ergebnis_audit();

DROP TABLE seminar_2_pruefung;
DROP TABLE seminar_2_pruefung_history;
DROP FUNCTION IF EXISTS seminar_2_pruefung_audit();

ALTER TABLE seminar_pruefung
    ADD COLUMN teilnehmer_2_seminar INTEGER NOT NULL REFERENCES teilnehmer_2_seminar (id);
ALTER TABLE seminar_pruefung
    ADD COLUMN antritt BOOLEAN;
ALTER TABLE seminar_pruefung
    ADD COLUMN begruendung INTEGER REFERENCES seminar_pruefung_begruendung (id);
ALTER TABLE seminar_pruefung
    ADD COLUMN ergebnis_type INTEGER REFERENCES seminar_pruefung_ergebnis_type (id);
ALTER TABLE seminar_pruefung
    ADD COLUMN ergebnis_in_prozent INTEGER;
ALTER TABLE seminar_pruefung
    ADD COLUMN pruefung_am DATE;


ALTER TABLE seminar_pruefung_history
    ADD COLUMN teilnehmer_2_seminar INTEGER;
ALTER TABLE seminar_pruefung_history
    ADD COLUMN antritt BOOLEAN;
ALTER TABLE seminar_pruefung_history
    ADD COLUMN begruendung INTEGER;
ALTER TABLE seminar_pruefung_history
    ADD COLUMN ergebnis_type INTEGER;
ALTER TABLE seminar_pruefung_history
    ADD COLUMN ergebnis_in_prozent INTEGER;
ALTER TABLE seminar_pruefung_history
    ADD COLUMN pruefung_am DATE;


CREATE
    OR REPLACE FUNCTION seminar_pruefung_audit() RETURNS TRIGGER
    LANGUAGE plpgsql
AS
$$
BEGIN
    IF
        TG_OP = 'DELETE' THEN
        INSERT INTO seminar_pruefung_history (seminar_pruefung_id, bezeichnung, pruefung_art, gegenstand, niveau,
                                              institut, created_on, created_by, changed_on, changed_by,
                                              action, action_timestamp, teilnehmer_2_seminar, antritt, begruendung,
                                              ergebnis_type, ergebnis_in_prozent, pruefung_am)
        VALUES (OLD.id,
                OLD.bezeichnung,
                OLD.pruefung_art,
                OLD.gegenstand,
                OLD.niveau,
                OLD.institut,
                OLD.created_on,
                OLD.created_by,
                OLD.changed_on,
                OLD.changed_by,
                'D', NOW(),
                OLD.teilnehmer_2_seminar,
                OLD.antritt,
                OLD.begruendung,
                OLD.ergebnis_type,
                OLD.ergebnis_in_prozent,
                OLD.pruefung_am);
        RETURN OLD;
    ELSIF
        TG_OP = 'UPDATE' THEN
        INSERT INTO seminar_pruefung_history (seminar_pruefung_id, bezeichnung, pruefung_art, gegenstand, niveau,
                                              institut, created_on, created_by, changed_on, changed_by,
                                              action, action_timestamp, teilnehmer_2_seminar, antritt, begruendung,
                                              ergebnis_type, ergebnis_in_prozent, pruefung_am)
        VALUES (NEW.id,
                NEW.bezeichnung,
                NEW.pruefung_art,
                NEW.gegenstand,
                NEW.niveau,
                NEW.institut,
                NEW.created_on,
                NEW.created_by,
                NEW.changed_on,
                NEW.changed_by, 'U', NOW(),
                NEW.teilnehmer_2_seminar,
                NEW.antritt,
                NEW.begruendung,
                NEW.ergebnis_type,
                NEW.ergebnis_in_prozent,
                NEW.pruefung_am);
        RETURN NEW;
    ELSIF
        TG_OP = 'INSERT' THEN
        INSERT INTO seminar_pruefung_history (seminar_pruefung_id, bezeichnung, pruefung_art, gegenstand, niveau,
                                              institut, created_on, created_by, changed_on, changed_by,
                                              action, action_timestamp, teilnehmer_2_seminar, antritt, begruendung,
                                              ergebnis_type, ergebnis_in_prozent, pruefung_am)
        VALUES (NEW.id,
                NEW.bezeichnung,
                NEW.pruefung_art,
                NEW.gegenstand,
                NEW.niveau,
                NEW.institut,
                NEW.created_on,
                NEW.created_by,
                NEW.changed_on,
                NEW.changed_by, 'I', NOW(),
                NEW.teilnehmer_2_seminar,
                NEW.antritt,
                NEW.begruendung,
                NEW.ergebnis_type,
                NEW.ergebnis_in_prozent,
                NEW.pruefung_am);

        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$;

ALTER FUNCTION seminar_pruefung_audit() OWNER TO ibosng;


UPDATE teilnehmer_notiz_type
SET name = INITCAP(name)
WHERE name IN ('intern', 'extern');

UPDATE seminar_pruefung_begruendung
SET name = UPPER(LEFT(name, 1)) || SUBSTRING(name FROM 2);

DELETE FROM seminar_pruefung_ergebnis_type WHERE TRUE;
INSERT INTO seminar_pruefung_ergebnis_type (name)
VALUES
    ('Bestanden'),
    ('Nicht bestanden'),
    ('Sehr gut'),
    ('Guter erfolg'),
    ('Ausgezeichneter Erfolg'),
    ('Teilgenommen'),
    ('(Angemeldet) Nicht teilgenommen');


ALTER TABLE teilnehmer_data_status
    DROP COLUMN teilnehmernotiz;
ALTER TABLE teilnehmer_data_status_history
    DROP COLUMN teilnehmernotiz;

CREATE
    OR REPLACE FUNCTION teilnehmer_data_status_audit() RETURNS TRIGGER
    LANGUAGE plpgsql
AS
$$
BEGIN
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO teilnehmer_data_status_history (teilnehmer_data_status_id, teilnehmer, teilnehmer2sprachkenntnis,
                                                    error, cause,
                                                    created_on, created_by, changed_by,
                                                    action,
                                                    action_timestamp)
        VALUES (OLD.id, OLD.teilnehmer, OLD.teilnehmer2sprachkenntnis, OLD.error,
                OLD.cause, OLD.created_on,
                OLD.created_by, OLD.changed_by, 'D',
                now());
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO teilnehmer_data_status_history (teilnehmer_data_status_id, teilnehmer, teilnehmer2sprachkenntnis,
                                                    error, cause,
                                                    created_on, created_by, changed_by,
                                                    action,
                                                    action_timestamp)
        VALUES (NEW.id, NEW.teilnehmer, NEW.teilnehmer2sprachkenntnis, NEW.error,
                NEW.cause, NEW.created_on,
                NEW.created_by, NEW.changed_by, 'U',
                now());
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO teilnehmer_data_status_history (teilnehmer_data_status_id, teilnehmer, teilnehmer2sprachkenntnis,
                                                    error, cause,
                                                    created_on, created_by, changed_by,
                                                    action,
                                                    action_timestamp)
        VALUES (NEW.id, NEW.teilnehmer, NEW.teilnehmer2sprachkenntnis, NEW.error,
                NEW.cause, NEW.created_on,
                NEW.created_by, NEW.changed_by, 'U',
                now());
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$;

ALTER FUNCTION teilnehmer_data_status_audit() OWNER TO ibosng;

ALTER TABLE Teilnehmer_2_seminar
    ADD COLUMN created_by TEXT DEFAULT CURRENT_USER NOT NULL,
    ADD COLUMN changed_on TIMESTAMP,
    ADD COLUMN changed_by TEXT;

ALTER TABLE seminar_2_trainer
    DROP CONSTRAINT IF EXISTS seminar_2_trainer_trainer_funktion_fkey;
ALTER TABLE seminar_2_trainer
    ALTER COLUMN trainer_funktion TYPE TEXT;
DROP FUNCTION IF EXISTS trainer_funktion_audit() CASCADE;
DROP TABLE IF EXISTS trainer_funktion_history CASCADE;
DROP TABLE IF EXISTS trainer_funktion CASCADE;