CREATE TABLE abwesenheit
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    grund        VARCHAR(255),
    beschreibung VARCHAR(255),
    kommentar    VARCHAR(255),
    art          VARCHAR(255),
    id_lhr       INTEGER,
    von          date,
    bis          date,
    typ          VARCHAR(255),
    tage         DOUBLE PRECISION,
    saldo        DOUBLE PRECISION,
    created_on   TIMESTAMP DEFAULT CURRENT_TIMESTAMP      NOT NULL,
    created_by   VARCHAR(255),
    changed_on   TIMESTAMP WITHOUT TIME ZONE,
    changed_by   VARCHAR(255),
    CONSTRAINT pk_abwesenheit PRIMARY KEY (id)
);

CREATE TABLE abwesenheit_history
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    abwesenheit_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    grund            VARCHAR(255),
    beschreibung     VARCHAR(255),
    kommentar        VARCHAR(255),
    art              VARCHAR(255),
    id_lhr           INTEGER,
    von              date,
    bis              date,
    typ              VARCHAR(255),
    tage             DOUBLE PRECISION,
    saldo            DOUBLE PRECISION,
    created_on       TIMESTAMP DEFAULT CURRENT_TIMESTAMP      NOT NULL,
    created_by       VARCHAR(255),
    changed_on       TIMESTAMP WITHOUT TIME ZONE,
    changed_by       VARCHAR(255),
    action           char,
    action_timestamp timestamp                                not null
);

create
or replace function abwesenheit_audit() returns trigger
    language plpgsql
    as
    $$
BEGIN
    IF
(TG_OP = 'DELETE') THEN
    INSERT INTO abwesenheit_history (abwesenheit_id,
        grund, beschreibung,kommentar,art,id_lhr,von,bis,typ,tage,saldo,
        created_on, created_by, changed_on, changed_by,
        action,
        action_timestamp)
    VALUES (OLD.id, OLD.grund, OLD.beschreibung, OLD.kommentar,OLD.art,OLD.id_lhr,OLD.von,OLD.bis,OLD.typ,OLD.tage,OLD.saldo,
        OLD.created_on, OLD.created_by, OLD.changed_on, OLD.changed_by, 'D',
        now());
RETURN OLD;
ELSIF
(TG_OP = 'UPDATE') THEN
    INSERT INTO abwesenheit_history (abwesenheit_id,grund, beschreibung,kommentar,art,id_lhr,von,bis,typ,tage,saldo,
       created_on, created_by, changed_on, changed_by,
       action,
       action_timestamp)
    VALUES (NEW.id, NEW.grund, NEW.beschreibung, NEW.kommentar,NEW.art,NEW.id_lhr,NEW.von,NEW.bis,NEW.typ,NEW.tage,NEW.saldo,
        NEW.created_on, NEW.created_by, NEW.changed_on, NEW.changed_by, 'U',
        now());
RETURN NEW;
ELSIF
(TG_OP = 'INSERT') THEN
    INSERT INTO abwesenheit_history (abwesenheit_id,grund, beschreibung,kommentar,art,id_lhr,von,bis,typ,tage,saldo,
                    created_on, created_by, changed_on, changed_by,
       action,
       action_timestamp)
    VALUES (NEW.id,  NEW.grund, NEW.beschreibung, NEW.kommentar,NEW.art,NEW.id_lhr,NEW.von,NEW.bis,NEW.typ,NEW.tage,NEW.saldo,
        NEW.created_on, NEW.created_by, NEW.changed_on, NEW.changed_by, 'I', now());
RETURN NEW;
END IF;
RETURN NULL; -- result is ignored since this is an AFTER trigger
END;
$$;

alter function abwesenheit_audit() owner to ibosng;

create trigger abwesenheit_insert
    after insert
    on abwesenheit
    for each row
    execute procedure abwesenheit_audit();

create trigger abwesenheit_update
    after update
    on abwesenheit
    for each row
    execute procedure abwesenheit_audit();

create trigger abwesenheit_delete
    after delete
    on abwesenheit
    for each row
    execute procedure abwesenheit_audit();