CREATE TABLE leistungserfassung
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    personalnummer  INTEGER references personalnummer,
    leistungsdatum  date,
    leistungstyp    VARCHAR(255), --enum
    created_on      TIMESTAMP DEFAULT CURRENT_TIMESTAMP      NOT NULL,
    created_by      VARCHAR(255),
    changed_on      TIMESTAMP WITHOUT TIME ZONE,
    changed_by      VARCHAR(255)
);

CREATE TABLE leistungserfassung_history
(
    id                     INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    leistungserfassung_id   INTEGER NOT NULL,
    personalnummer         INTEGER,
    leistungsdatum         DATE,
    leistungstyp           VARCHAR(255),
    created_on             TIMESTAMP,
    created_by             VARCHAR(255),
    changed_on             TIMESTAMP,
    changed_by             VARCHAR(255),
    action                 CHAR(1),
    action_timestamp       TIMESTAMP NOT NULL
);

CREATE OR REPLACE FUNCTION leistungserfassung_audit() RETURNS TRIGGER
LANGUAGE plpgsql
AS
$$
BEGIN
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO leistungserfassung_history (leistungserfassung_id, personalnummer, leistungsdatum, leistungstyp,
                                                created_on, created_by, changed_on, changed_by,
                                                action, action_timestamp)
        VALUES (OLD.id, OLD.personalnummer, OLD.leistungsdatum, OLD.leistungstyp,
                OLD.created_on, OLD.created_by, OLD.changed_on, OLD.changed_by, 'D', NOW());
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO leistungserfassung_history (leistungserfassung_id, personalnummer, leistungsdatum, leistungstyp,
                                                created_on, created_by, changed_on, changed_by,
                                                action, action_timestamp)
        VALUES (NEW.id, NEW.personalnummer, NEW.leistungsdatum, NEW.leistungstyp,
                NEW.created_on, NEW.created_by, NEW.changed_on, NEW.changed_by, 'U', NOW());
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO leistungserfassung_history (leistungserfassung_id, personalnummer, leistungsdatum, leistungstyp,
                                                created_on, created_by, changed_on, changed_by,
                                                action, action_timestamp)
        VALUES (NEW.id, NEW.personalnummer, NEW.leistungsdatum, NEW.leistungstyp,
                NEW.created_on, NEW.created_by, NEW.changed_on, NEW.changed_by, 'I', NOW());
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$;

CREATE TRIGGER leistungserfassung_insert
    AFTER INSERT ON leistungserfassung
    FOR EACH ROW
EXECUTE FUNCTION leistungserfassung_audit();

CREATE TRIGGER leistungserfassung_update
    AFTER UPDATE ON leistungserfassung
    FOR EACH ROW
EXECUTE FUNCTION leistungserfassung_audit();

CREATE TRIGGER leistungserfassung_delete
    AFTER DELETE ON leistungserfassung
    FOR EACH ROW
EXECUTE FUNCTION leistungserfassung_audit();


CREATE TABLE zeitbuchuntyp
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    type            VARCHAR(255),
    created_on      TIMESTAMP DEFAULT CURRENT_TIMESTAMP      NOT NULL,
    created_by      VARCHAR(255),
    changed_on      TIMESTAMP WITHOUT TIME ZONE,
    changed_by      VARCHAR(255)
);

CREATE TABLE zeitbuchuntyp_history
(
    id                  INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    zeitbuchuntyp_id     INTEGER NOT NULL,
    type                VARCHAR(255),
    created_on           TIMESTAMP,
    created_by           VARCHAR(255),
    changed_on           TIMESTAMP,
    changed_by           VARCHAR(255),
    action               CHAR(1),
    action_timestamp     TIMESTAMP NOT NULL
);

CREATE OR REPLACE FUNCTION zeitbuchuntyp_audit() RETURNS TRIGGER
LANGUAGE plpgsql
AS
$$
BEGIN
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO zeitbuchuntyp_history (zeitbuchuntyp_id, type,
                                           created_on, created_by, changed_on, changed_by,
                                           action, action_timestamp)
        VALUES (OLD.id, OLD.type,
                OLD.created_on, OLD.created_by, OLD.changed_on, OLD.changed_by, 'D', NOW());
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO zeitbuchuntyp_history (zeitbuchuntyp_id, type,
                                           created_on, created_by, changed_on, changed_by,
                                           action, action_timestamp)
        VALUES (NEW.id, NEW.type,
                NEW.created_on, NEW.created_by, NEW.changed_on, NEW.changed_by, 'U', NOW());
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO zeitbuchuntyp_history (zeitbuchuntyp_id, type,
                                           created_on, created_by, changed_on, changed_by,
                                           action, action_timestamp)
        VALUES (NEW.id, NEW.type,
                NEW.created_on, NEW.created_by, NEW.changed_on, NEW.changed_by, 'I', NOW());
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$;

CREATE TRIGGER zeitbuchuntyp_insert
    AFTER INSERT ON zeitbuchuntyp
    FOR EACH ROW
EXECUTE FUNCTION zeitbuchuntyp_audit();

CREATE TRIGGER zeitbuchuntyp_update
    AFTER UPDATE ON zeitbuchuntyp
    FOR EACH ROW
EXECUTE FUNCTION zeitbuchuntyp_audit();

CREATE TRIGGER zeitbuchuntyp_delete
    AFTER DELETE ON zeitbuchuntyp
    FOR EACH ROW
EXECUTE FUNCTION zeitbuchuntyp_audit();

CREATE TABLE zeitbuchung
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    von                 time,
    bis                 time,
    pause_von            time,
    pause_bis            time,
    dauer_std            double precision,
    an_abwesenheit      boolean,
    leistungsort        VARCHAR(255),--enum
    seminar             integer references seminar,
    zeitbuchuntyp       integer references zeitbuchuntyp,
    leistungserfassung   integer references leistungserfassung,
    kostenstelle        integer references kostenstelle,
    created_on          TIMESTAMP DEFAULT CURRENT_TIMESTAMP      NOT NULL,
    created_by          VARCHAR(255),
    changed_on          TIMESTAMP WITHOUT TIME ZONE,
    changed_by          VARCHAR(255)
);

CREATE TABLE zeitbuchung_history
(
    id                    INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    zeitbuchung_id         INTEGER NOT NULL,
    von                   TIME,
    bis                   TIME,
    pause_von              TIME,
    pause_bis              TIME,
    dauer_std              DOUBLE PRECISION,
    an_abwesenheit        BOOLEAN,
    leistungsort          VARCHAR(255),
    seminar               INTEGER,
    zeitbuchuntyp         INTEGER,
    leistungserfassung     INTEGER,
    kostenstelle          INTEGER,
    created_on            TIMESTAMP,
    created_by            VARCHAR(255),
    changed_on            TIMESTAMP,
    changed_by            VARCHAR(255),
    action                CHAR(1),
    action_timestamp      TIMESTAMP NOT NULL
);

CREATE OR REPLACE FUNCTION zeitbuchung_audit() RETURNS TRIGGER
LANGUAGE plpgsql
AS
$$
BEGIN
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO zeitbuchung_history (zeitbuchung_id, von, bis, pause_von, pause_bis, dauer_std, an_abwesenheit, leistungsort,
                                         seminar, zeitbuchuntyp, leistungserfassung, kostenstelle,
                                         created_on, created_by, changed_on, changed_by,
                                         action, action_timestamp)
        VALUES (OLD.id, OLD.von, OLD.bis, OLD.pause_von, OLD.pause_bis, OLD.dauer_std, OLD.an_abwesenheit, OLD.leistungsort,
                OLD.seminar, OLD.zeitbuchuntyp, OLD.leistungserfassung, OLD.kostenstelle,
                OLD.created_on, OLD.created_by, OLD.changed_on, OLD.changed_by, 'D', NOW());
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO zeitbuchung_history (zeitbuchung_id, von, bis, pause_von, pause_bis, dauer_std, an_abwesenheit, leistungsort,
                                         seminar, zeitbuchuntyp, leistungserfassung, kostenstelle,
                                         created_on, created_by, changed_on, changed_by,
                                         action, action_timestamp)
        VALUES (NEW.id, NEW.von, NEW.bis, NEW.pause_von, NEW.pause_bis, NEW.dauer_std, NEW.an_abwesenheit, NEW.leistungsort,
                NEW.seminar, NEW.zeitbuchuntyp, NEW.leistungserfassung, NEW.kostenstelle,
                NEW.created_on, NEW.created_by, NEW.changed_on, NEW.changed_by, 'U', NOW());
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO zeitbuchung_history (zeitbuchung_id, von, bis, pause_von, pause_bis, dauer_std, an_abwesenheit, leistungsort,
                                         seminar, zeitbuchuntyp, leistungserfassung, kostenstelle,
                                         created_on, created_by, changed_on, changed_by,
                                         action, action_timestamp)
        VALUES (NEW.id, NEW.von, NEW.bis, NEW.pause_von, NEW.pause_bis, NEW.dauer_std, NEW.an_abwesenheit, NEW.leistungsort,
                NEW.seminar, NEW.zeitbuchuntyp, NEW.leistungserfassung, NEW.kostenstelle,
                NEW.created_on, NEW.created_by, NEW.changed_on, NEW.changed_by, 'I', NOW());
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$;

CREATE TRIGGER zeitbuchung_insert
    AFTER INSERT ON zeitbuchung
    FOR EACH ROW
EXECUTE FUNCTION zeitbuchung_audit();

CREATE TRIGGER zeitbuchung_update
    AFTER UPDATE ON zeitbuchung
    FOR EACH ROW
EXECUTE FUNCTION zeitbuchung_audit();

CREATE TRIGGER zeitbuchung_delete
    AFTER DELETE ON zeitbuchung
    FOR EACH ROW
EXECUTE FUNCTION zeitbuchung_audit();
