
CREATE TABLE urlaubsdaten (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personalnummer   INTEGER NOT NULL REFERENCES personalnummer(id),
    anspruch_type    INTEGER NOT NULL REFERENCES anspruch(id),
    month            DATE,
    from_date        DATE,
    next_anspruch    DATE,
    kuerzung         DOUBLE PRECISION,
    verjaehrung      DOUBLE PRECISION,
    anspruch         DOUBLE PRECISION,
    konsum           DOUBLE PRECISION,
    rest             DOUBLE PRECISION,
    created_on       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by       VARCHAR(255),
    changed_on       TIMESTAMP,
    changed_by       VARCHAR(255)
);

CREATE TABLE urlaubsdaten_history (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    urlaubsdaten_id   INTEGER,
    personalnummer    INTEGER,
    anspruch_type     INTEGER,
    month             DATE,
    from_date         DATE,
    next_anspruch     DATE,
    kuerzung          DOUBLE PRECISION,
    verjaehrung       DOUBLE PRECISION,
    anspruch          DOUBLE PRECISION,
    konsum            DOUBLE PRECISION,
    rest              DOUBLE PRECISION,
    created_on        TIMESTAMP,
    created_by        VARCHAR(255),
    changed_on        TIMESTAMP,
    changed_by        VARCHAR(255),
    action            CHAR,
    action_timestamp  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE OR REPLACE FUNCTION urlaubsdaten_audit() RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        INSERT INTO urlaubsdaten_history (urlaubsdaten_id, personalnummer, anspruch_type, month, from_date, next_anspruch, kuerzung, verjaehrung, anspruch, konsum, rest, created_on, created_by, changed_on, changed_by, action, action_timestamp)
        VALUES (OLD.id, OLD.personalnummer, OLD.anspruch_type, OLD.month, OLD.from_date, OLD.next_anspruch, OLD.kuerzung, OLD.verjaehrung, OLD.anspruch, OLD.konsum, OLD.rest, OLD.created_on, OLD.created_by, OLD.changed_on, OLD.changed_by, 'D', NOW());
        RETURN OLD;
    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO urlaubsdaten_history (urlaubsdaten_id, personalnummer, anspruch_type, month, from_date, next_anspruch, kuerzung, verjaehrung, anspruch, konsum, rest, created_on, created_by, changed_on, changed_by, action, action_timestamp)
        VALUES (NEW.id, NEW.personalnummer, NEW.anspruch_type, NEW.month, NEW.from_date, NEW.next_anspruch, NEW.kuerzung, NEW.verjaehrung, NEW.anspruch, NEW.konsum, NEW.rest, NEW.created_on, NEW.created_by, NEW.changed_on, NEW.changed_by, 'U', NOW());
        RETURN NEW;
    ELSIF TG_OP = 'INSERT' THEN
        INSERT INTO urlaubsdaten_history (urlaubsdaten_id, personalnummer, anspruch_type, month, from_date, next_anspruch, kuerzung, verjaehrung, anspruch, konsum, rest, created_on, created_by, changed_on, changed_by, action, action_timestamp)
        VALUES (NEW.id, NEW.personalnummer, NEW.anspruch_type, NEW.month, NEW.from_date, NEW.next_anspruch, NEW.kuerzung, NEW.verjaehrung, NEW.anspruch, NEW.konsum, NEW.rest, NEW.created_on, NEW.created_by, NEW.changed_on, NEW.changed_by, 'I', NOW());
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$;

ALTER FUNCTION urlaubsdaten_audit() OWNER TO ibosng;

CREATE TRIGGER urlaubsdaten_insert
AFTER INSERT ON urlaubsdaten
FOR EACH ROW
EXECUTE FUNCTION urlaubsdaten_audit();

CREATE TRIGGER urlaubsdaten_update
AFTER UPDATE ON urlaubsdaten
FOR EACH ROW
EXECUTE FUNCTION urlaubsdaten_audit();

CREATE TRIGGER urlaubsdaten_delete
AFTER DELETE ON urlaubsdaten
FOR EACH ROW
EXECUTE FUNCTION urlaubsdaten_audit();