INSERT INTO teilnehmer_notiz_kategorie (name)
VALUES ('Seminarverlauf'),
       ('BBE - extern'),
       ('Vermittlung'),
       ('Bewerbungstraining'),
       ('Berufsorientierung'),
       ('Karriereplanung');

CREATE TABLE teilnehmer_notiz_type
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT                                NOT NULL,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by TEXT      default CURRENT_USER      NOT NULL,
    changed_on TIMESTAMP,
    changed_by TEXT,
    status     smallint                            NOT NULL DEFAULT 1
);

CREATE TABLE teilnehmer_notiz_type_history
(
    id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teilnehmer_notiz_type_id INTEGER                             NOT NULL,
    name                     TEXT                                NOT NULL,
    created_on               TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by               TEXT      default CURRENT_USER      NOT NULL,
    changed_on               TIMESTAMP,
    changed_by               TEXT,
    status                   smallint                            NOT NULL DEFAULT 1,
    action                   CHAR,
    action_timestamp         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE
    OR REPLACE FUNCTION teilnehmer_notiz_type_audit() RETURNS TRIGGER
    LANGUAGE plpgsql
AS
$$
BEGIN
    IF
        TG_OP = 'DELETE' THEN
        INSERT INTO teilnehmer_notiz_type_history (teilnehmer_notiz_type_id, name, created_on, created_by,
                                                   changed_on, changed_by, status,
                                                   action, action_timestamp)
        VALUES (OLD.id,
                OLD.name,
                OLD.created_on,
                OLD.created_by,
                OLD.changed_on,
                OLD.changed_by,
                OLD.status,
                'D', NOW());
        RETURN OLD;
    ELSIF
        TG_OP = 'UPDATE' THEN
        INSERT INTO teilnehmer_notiz_type_history (teilnehmer_notiz_type_id, name, created_on, created_by,
                                                   changed_on, changed_by, status,
                                                   action, action_timestamp)
        VALUES (NEW.id,
                NEW.name,
                NEW.created_on,
                NEW.created_by,
                NEW.changed_on,
                NEW.changed_by,
                NEW.status, 'U', NOW());
        RETURN NEW;
    ELSIF
        TG_OP = 'INSERT' THEN
        INSERT INTO teilnehmer_notiz_type_history (teilnehmer_notiz_type_id, name, created_on, created_by,
                                                   changed_on, changed_by, status,
                                                   action, action_timestamp)
        VALUES (NEW.id,
                NEW.name,
                NEW.created_on,
                NEW.created_by,
                NEW.changed_on,
                NEW.changed_by,
                NEW.status, 'I', NOW());

        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$;

ALTER FUNCTION teilnehmer_notiz_type_audit() OWNER TO ibosng;

CREATE TRIGGER teilnehmer_notiz_type_insert
    AFTER INSERT
    ON teilnehmer_notiz_type
    FOR EACH ROW
EXECUTE PROCEDURE teilnehmer_notiz_type_audit();

CREATE TRIGGER teilnehmer_notiz_type_update
    AFTER UPDATE
    ON teilnehmer_notiz_type
    FOR EACH ROW
EXECUTE PROCEDURE teilnehmer_notiz_type_audit();

CREATE TRIGGER teilnehmer_notiz_type_delete
    AFTER DELETE
    ON teilnehmer_notiz_type
    FOR EACH ROW
EXECUTE PROCEDURE teilnehmer_notiz_type_audit();

INSERT INTO teilnehmer_notiz_type (name)
VALUES ('intern'),
       ('extern');


ALTER TABLE teilnehmer_notiz
    ADD COLUMN type INTEGER REFERENCES teilnehmer_notiz_type (id);
ALTER TABLE teilnehmer_notiz_history
    ADD COLUMN type INTEGER;


CREATE
    OR REPLACE FUNCTION teilnehmer_notiz_audit() RETURNS TRIGGER
    LANGUAGE plpgsql
AS
$$
BEGIN
    IF
        TG_OP = 'DELETE' THEN
        INSERT INTO teilnehmer_notiz_history (teilnehmer_notiz_id, teilnehmer, notiz, kategorie, created_on, created_by,
                                              changed_on,
                                              changed_by, action, action_timestamp, type)
        VALUES (OLD.id,
                OLD.teilnehmer,
                OLD.notiz,
                OLD.kategorie,
                OLD.created_on,
                OLD.created_by,
                OLD.changed_on,
                OLD.changed_by,
                'D',
                NOW(),
                OLD.type);
        RETURN OLD;
    ELSIF
        TG_OP = 'UPDATE' THEN
        INSERT INTO teilnehmer_notiz_history (teilnehmer_notiz_id, teilnehmer, notiz, kategorie, created_on, created_by,
                                              changed_on,
                                              changed_by, action, action_timestamp, type)
        VALUES (NEW.id,
                NEW.teilnehmer,
                NEW.notiz,
                NEW.kategorie,
                NEW.created_on,
                NEW.created_by,
                NEW.changed_on,
                NEW.changed_by,
                'U',
                NOW(),
                NEW.type);
        RETURN NEW;
    ELSIF
        TG_OP = 'INSERT' THEN
        INSERT INTO teilnehmer_notiz_history (teilnehmer_notiz_id, teilnehmer, notiz, kategorie, created_on, created_by,
                                              changed_on,
                                              changed_by, action, action_timestamp, type)
        VALUES (NEW.id,
                NEW.teilnehmer,
                NEW.notiz,
                NEW.kategorie,
                NEW.created_on,
                NEW.created_by,
                NEW.changed_on,
                NEW.changed_by,
                'I',
                NOW(),
                NEW.type);

        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$;

ALTER FUNCTION teilnehmer_notiz_audit() OWNER TO ibosng;