CREATE TABLE verwandtschaft
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255),
    lhr_kz VARCHAR(255),
    status      smallint  not null,
    created_on   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by   VARCHAR(255),
    changed_on   TIMESTAMP WITHOUT TIME ZONE,
    changed_by   VARCHAR(255)
);

CREATE TABLE verwandtschaft_history
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    verwandtschaft_id INTEGER                             NOT NULL,
    name             VARCHAR(255),
    lhr_kz      VARCHAR(255),
    status      smallint  not null,
    created_on        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by        VARCHAR(255),
    changed_on        TIMESTAMP WITHOUT TIME ZONE,
    changed_by        VARCHAR(255),
    action            CHAR,
    action_timestamp  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE
OR REPLACE FUNCTION verwandtschaft_audit() RETURNS TRIGGER
    LANGUAGE plpgsql
AS
$$
BEGIN
    IF
TG_OP = 'DELETE' THEN
        INSERT INTO verwandtschaft_history (verwandtschaft_id, name, lhr_kz, status, created_on, created_by , changed_on, changed_by, action, action_timestamp)
        VALUES (OLD.id, OLD.name, OLD.lhr_kz, OLD.status, OLD.created_on, OLD.created_by, OLD.changed_on, OLD.changed_by, 'D', NOW());
RETURN OLD;
ELSIF
TG_OP = 'UPDATE' THEN
        INSERT INTO verwandtschaft_history (verwandtschaft_id, name, lhr_kz, status, created_on, created_by , changed_on, changed_by, action, action_timestamp)
        VALUES (NEW.id, NEW.name, NEW.lhr_kz, NEW.beschreibung, NEW.status, NEW.created_on, NEW.created_by , NEW.changed_on, NEW.changed_by, 'U', NOW());
RETURN NEW;
ELSIF
TG_OP = 'INSERT' THEN
        INSERT INTO verwandtschaft_history (verwandtschaft_id, name, lhr_kz, status, created_on, created_by , changed_on, changed_by, action, action_timestamp)
        VALUES (NEW.id, NEW.name, NEW.lhr_kz, NEW.status, NEW.created_on, NEW.created_by , NEW.changed_on, NEW.changed_by, 'I', NOW());
RETURN NEW;
END IF;
RETURN NULL; -- result is ignored since this is an AFTER trigger
END;
$$;

alter function verwandtschaft_audit() owner to ibosng;

CREATE TRIGGER verwandtschaft_insert
    AFTER INSERT
    ON verwandtschaft
    FOR EACH ROW
    EXECUTE FUNCTION verwandtschaft_audit();

CREATE TRIGGER verwandtschaft_update
    AFTER UPDATE
    ON verwandtschaft
    FOR EACH ROW
    EXECUTE FUNCTION verwandtschaft_audit();

CREATE TRIGGER verwandtschaft_delete
    AFTER DELETE
    ON verwandtschaft
    FOR EACH ROW
    EXECUTE FUNCTION verwandtschaft_audit();



INSERT INTO verwandtschaft(name, lhr_kz, status, created_by)
VALUES ('Tochter', 'T', 1, current_user),
       ('Sohn', 'S', 1, current_user),
       ('Ehegatte', 'G', 1, current_user),
       ('geschiedener Ehegatte', 'E', 1, current_user),
       ('Lebensgemeinschaft', 'L', 1, current_user),
       ('Vater', 'V', 1, current_user),
       ('Mutter', 'M', 1, current_user),
       ('Witwe/Waise', 'W', 1, current_user),
       ('Enkelkind', 'K', 1, current_user),
       ('Pflegekind', 'H', 1, current_user),
       ('Partner', 'P', 1, current_user),
       ('Ehem. Partner - Gericht', 'A', 1, current_user),
       ('Ehem. Partner - Tod', 'X', 1, current_user),
       ('Diverse', 'D', 1, current_user);