-- Create the 'zeitspeicher' table
CREATE TABLE IF NOT EXISTS zeitspeicher (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zeitspeicher_nummer INTEGER,
    name TEXT,
    abbreviation TEXT,
    comment TEXT,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by TEXT NOT NULL,
    changed_on TIMESTAMP,
    changed_by TEXT
);

ALTER TABLE zeitspeicher
    OWNER TO ibosng;

-- Create the 'zeitspeicher_history' table
CREATE TABLE IF NOT EXISTS zeitspeicher_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zeitspeicher_id INTEGER NOT NULL REFERENCES zeitspeicher(id),
    zeitspeicher_nummer INTEGER,
    name TEXT,
    abbreviation TEXT,
    comment TEXT,
    created_on TIMESTAMP NOT NULL,
    created_by TEXT NOT NULL,
    changed_on TIMESTAMP,
    changed_by TEXT,
    action CHAR,
    action_timestamp TIMESTAMP NOT NULL
    );

ALTER TABLE zeitspeicher_history
    OWNER TO ibosng;

-- Create the 'zeitspeicher_audit' function
CREATE OR REPLACE FUNCTION zeitspeicher_audit() RETURNS TRIGGER
    LANGUAGE plpgsql
AS
$$
BEGIN
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO zeitspeicher_history (zeitspeicher_id, zeitspeicher_nummer, name, abbreviation, comment,
                                          created_on, created_by, changed_on, changed_by,
                                          action, action_timestamp)
        VALUES (OLD.id, OLD.zeitspeicher_nummer, OLD.name, OLD.abbreviation, OLD.comment,
                OLD.created_on, OLD.created_by, OLD.changed_on, OLD.changed_by,
                'D', NOW());
RETURN OLD;
ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO zeitspeicher_history (zeitspeicher_id, zeitspeicher_nummer, name, abbreviation, comment,
                                          created_on, created_by, changed_on, changed_by,
                                          action, action_timestamp)
        VALUES (NEW.id, NEW.zeitspeicher_nummer, NEW.name, NEW.abbreviation, NEW.comment,
                NEW.created_on, NEW.created_by, NEW.changed_on, NEW.changed_by,
                'U', NOW());
RETURN NEW;
ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO zeitspeicher_history (zeitspeicher_id, zeitspeicher_nummer, name, abbreviation, comment,
                                          created_on, created_by, changed_on, changed_by,
                                          action, action_timestamp)
        VALUES (NEW.id, NEW.zeitspeicher_nummer, NEW.name, NEW.abbreviation, NEW.comment,
                NEW.created_on, NEW.created_by, NEW.changed_on, NEW.changed_by,
                'I', NOW());
RETURN NEW;
END IF;
RETURN NULL;
END;
$$;

ALTER FUNCTION zeitspeicher_audit() OWNER TO ibosng;

-- Create triggers for the 'zeitspeicher' table
CREATE TRIGGER zeitspeicher_insert
    AFTER INSERT
    ON zeitspeicher
    FOR EACH ROW
    EXECUTE PROCEDURE zeitspeicher_audit();

CREATE TRIGGER zeitspeicher_update
    AFTER UPDATE
    ON zeitspeicher
    FOR EACH ROW
    EXECUTE PROCEDURE zeitspeicher_audit();

CREATE TRIGGER zeitspeicher_delete
    AFTER DELETE
    ON zeitspeicher
    FOR EACH ROW
    EXECUTE PROCEDURE zeitspeicher_audit();



-- Create the 'auszahlungsantrag' table
-- Create the 'auszahlungsantrag' table
CREATE TABLE IF NOT EXISTS auszahlungsantrag (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personalnummer_id INTEGER NOT NULL REFERENCES personalnummer(id),
    zeitspeicher_id INTEGER REFERENCES zeitspeicher(id),
    anfrage_nummer INTEGER,
    anzahl_minuten BIGINT,
    status TEXT,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by TEXT NOT NULL,
    changed_on TIMESTAMP ,
    changed_by TEXT
    );

ALTER TABLE auszahlungsantrag
    OWNER TO ibosng;

-- Create the 'auszahlungsantrag_history' table
CREATE TABLE IF NOT EXISTS auszahlungsantrag_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auszahlungsantrag_id INTEGER NOT NULL REFERENCES auszahlungsantrag(id),
    personalnummer_id INTEGER NOT NULL,
    zeitspeicher_id INTEGER,
    anfrage_nummer INTEGER,
    anzahl_minuten BIGINT,
    status TEXT,
    created_on TIMESTAMP NOT NULL,
    created_by TEXT NOT NULL,
    changed_on TIMESTAMP,
    changed_by TEXT,
    action CHAR,
    action_timestamp TIMESTAMP NOT NULL
    );

ALTER TABLE auszahlungsantrag_history
    OWNER TO ibosng;

-- Create the 'auszahlungsantrag_audit' function
CREATE OR REPLACE FUNCTION auszahlungsantrag_audit() RETURNS TRIGGER
    LANGUAGE plpgsql
AS
$$
BEGIN
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO auszahlungsantrag_history (auszahlungsantrag_id, personalnummer_id, zeitspeicher_id, anfrage_nummer, anzahl_minuten,
                                               status, created_on, created_by, changed_on, changed_by,
                                               action, action_timestamp)
        VALUES (OLD.id, OLD.personalnummer_id, OLD.zeitspeicher_id, OLD.anfrage_nummer, OLD.anzahl_minuten,
                OLD.status, OLD.created_on, OLD.created_by, OLD.changed_on, OLD.changed_by,
                'D', NOW());
RETURN OLD;
ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO auszahlungsantrag_history (auszahlungsantrag_id, personalnummer_id, zeitspeicher_id, anfrage_nummer, anzahl_minuten,
                                               status, created_on, created_by, changed_on, changed_by,
                                               action, action_timestamp)
        VALUES (NEW.id, NEW.personalnummer_id, NEW.zeitspeicher_id, NEW.anfrage_nummer, NEW.anzahl_minuten,
                NEW.status, NEW.created_on, NEW.created_by, NEW.changed_on, NEW.changed_by,
                'U', NOW());
RETURN NEW;
ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO auszahlungsantrag_history (auszahlungsantrag_id, personalnummer_id, zeitspeicher_id, anfrage_nummer, anzahl_minuten,
                                               status, created_on, created_by, changed_on, changed_by,
                                               action, action_timestamp)
        VALUES (NEW.id, NEW.personalnummer_id, NEW.zeitspeicher_id, NEW.anfrage_nummer, NEW.anzahl_minuten,
                NEW.status, NEW.created_on, NEW.created_by, NEW.changed_on, NEW.changed_by,
                'I', NOW());
RETURN NEW;
END IF;
RETURN NULL;
END;
$$;

ALTER FUNCTION auszahlungsantrag_audit() OWNER TO ibosng;

-- Create triggers for the 'auszahlungsantrag' table
CREATE TRIGGER auszahlungsantrag_insert
    AFTER INSERT
    ON auszahlungsantrag
    FOR EACH ROW
    EXECUTE PROCEDURE auszahlungsantrag_audit();

CREATE TRIGGER auszahlungsantrag_update
    AFTER UPDATE
    ON auszahlungsantrag
    FOR EACH ROW
    EXECUTE PROCEDURE auszahlungsantrag_audit();

CREATE TRIGGER auszahlungsantrag_delete
    AFTER DELETE
    ON auszahlungsantrag
    FOR EACH ROW
    EXECUTE PROCEDURE auszahlungsantrag_audit();



-- Populate mapping table
INSERT INTO zeitspeicher (zeitspeicher_nummer, name, abbreviation, comment, created_on, created_by)
VALUES
    (35, '+/- pro Tag', '+/-', Null, CURRENT_TIMESTAMP, current_user),
    (23, '3Monat-Umbuchung', '3MUmb', 'Hilfsspeicher für Fixzeit 3-Monatszeitraum', CURRENT_TIMESTAMP, current_user),
    (58, 'abgezogene Überstundenpauschale', 'aÜP', 'Tatsächliche abgezogene Überstunden (Pauschale)', CURRENT_TIMESTAMP, current_user),
    (46, 'Gesamtsaldo', 'GS', 'Summe aus Saldo und ZG als Info für Dienstnehmer', CURRENT_TIMESTAMP, current_user),
    (54, 'Ist täglich', 'Ist', 'Gearbeitete Zeit am Tag inkl. Überstunden', CURRENT_TIMESTAMP, current_user),
    (48, 'Ibis Event', 'ibis', 'Speichert gearbeitete Stunden nur in Speicher 48', CURRENT_TIMESTAMP, current_user),
    (49, 'Ibis Konsum', 'ibisk', 'Konsum verringert nur Speicher 49', CURRENT_TIMESTAMP, current_user),
    (3, 'Saldo', 'Saldo', Null, CURRENT_TIMESTAMP, current_user),
    (43, 'Soll', 'Soll', Null, CURRENT_TIMESTAMP, current_user),
    (22, 'Überstundenpauschale', 'ÜP', 'Überstundenpauschale aus persönlichen Satz', CURRENT_TIMESTAMP, current_user),
    (9, 'UeSt 50% frei', '50%f', 'Wird am Monatsende 1:1,5 in ZG (31) umgebucht', CURRENT_TIMESTAMP, current_user),
    (25, 'UeSt 50% pflichtig', '50%p', 'Wird am Monatsende 1:1,5 in ZG (31) umgebucht', CURRENT_TIMESTAMP, current_user),
    (55, 'UeSt 50% Summe', 'Ü50%', 'Summe aus 50% frei und 50% pflichtig als Info für Dienstnehmer', CURRENT_TIMESTAMP, current_user),
    (29, 'UeSt 100% frei', '100%f', 'Wird am Monatsende 1:1 in ZG (31) umgebucht', CURRENT_TIMESTAMP, current_user),
    (30, 'UeSt 100% pflichtig', '100%p', 'Wird am Monatsende 1:1 in ZG (31) umgebucht', CURRENT_TIMESTAMP, current_user),
    (56, 'UeSt 100% Summe', 'Ü100%', 'Summe aus 100% frei und 100% pflichtig als Info für Dienstnehmer', CURRENT_TIMESTAMP, current_user),
    (36, 'UeSt 25% frei', '25%f', 'Wird am Monatsende 1:1,25 in ZG (31) umgebucht', CURRENT_TIMESTAMP, current_user),
    (38, 'UeSt 25% pflichtig', '25%p', 'Wird am Monatsende 1:1,25 in ZG (31) umgebucht', CURRENT_TIMESTAMP, current_user),
    (57, 'UeSt 25% Summe', 'Ü25%', 'Summe aus 25% frei und 25% pflichtig als Info für Dienstnehmer', CURRENT_TIMESTAMP, current_user),
    (4, 'Wochenstunden', 'Woche', Null, CURRENT_TIMESTAMP, current_user),
    (31, 'ZeitausGleich', 'ZG', '1:1 Stunden', CURRENT_TIMESTAMP, current_user);

