CREATE TABLE klasse
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255),
    lhr_kz VARCHAR(255),
    beschreibung VARCHAR(255),
    status      smallint  not null,
    created_on   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by   VARCHAR(255),
    changed_on   TIMESTAMP WITHOUT TIME ZONE,
    changed_by   VARCHAR(255)
);

CREATE TABLE klasse_history
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    klasse_id INTEGER                             NOT NULL,
    name             VARCHAR(255),
    lhr_kz      VARCHAR(255),
    beschreibung VARCHAR(255),
    status      smallint  not null,
    created_on        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by        VARCHAR(255),
    changed_on        TIMESTAMP WITHOUT TIME ZONE,
    changed_by        VARCHAR(255),
    action            CHAR,
    action_timestamp  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE
OR REPLACE FUNCTION klasse_audit() RETURNS TRIGGER
    LANGUAGE plpgsql
AS
$$
BEGIN
    IF
TG_OP = 'DELETE' THEN
        INSERT INTO klasse_history (klasse_id, name, lhr_kz, beschreibung, status, created_on, created_by , changed_on, changed_by, action, action_timestamp)
        VALUES (OLD.id, OLD.name, OLD.lhr_kz, OLD.beschreibung, OLD.status, OLD.created_on, OLD.created_by, OLD.changed_on, OLD.changed_by, 'D', NOW());
RETURN OLD;
ELSIF
TG_OP = 'UPDATE' THEN
        INSERT INTO klasse_history (klasse_id, name, lhr_kz, beschreibung, status, created_on, created_by , changed_on, changed_by, action, action_timestamp)
        VALUES (NEW.id, NEW.name, NEW.lhr_kz, NEW.beschreibung, NEW.status, NEW.created_on, NEW.created_by , NEW.changed_on, NEW.changed_by, 'U', NOW());
RETURN NEW;
ELSIF
TG_OP = 'INSERT' THEN
        INSERT INTO klasse_history (klasse_id, name, lhr_kz, beschreibung, status, created_on, created_by , changed_on, changed_by, action, action_timestamp)
        VALUES (NEW.id, NEW.name, NEW.lhr_kz, NEW.beschreibung, NEW.status, NEW.created_on, NEW.created_by , NEW.changed_on, NEW.changed_by, 'I', NOW());
RETURN NEW;
END IF;
RETURN NULL; -- result is ignored since this is an AFTER trigger
END;
$$;

alter function klasse_audit() owner to ibosng;

CREATE TRIGGER klasse_insert
    AFTER INSERT
    ON klasse
    FOR EACH ROW
    EXECUTE FUNCTION klasse_audit();

CREATE TRIGGER klasse_update
    AFTER UPDATE
    ON klasse
    FOR EACH ROW
    EXECUTE FUNCTION klasse_audit();

CREATE TRIGGER klasse_delete
    AFTER DELETE
    ON klasse
    FOR EACH ROW
    EXECUTE FUNCTION klasse_audit();



INSERT INTO klasse(name, lhr_kz, beschreibung, status, created_by)
VALUES ('ÜBA', 'AMS', 'Überbetriebliche Ausbildung normal §30b', 1, current_user),
       ('ÜBV', 'ÜBV', 'Überbetriebliche Ausbildung Verlängert §8b', 1, current_user);