CREATE TABLE muttersprache
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT,
    kennzeichen_iso_639_1 TEXT,
    kennzeichen_iso_639_2 TEXT,
    kennzeichen_iso_639_3 TEXT,
    status      smallint  not null,
    created_on   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by   VARCHAR(255),
    changed_on   TIMESTAMP WITHOUT TIME ZONE,
    changed_by   VARCHAR(255)
);

CREATE TABLE muttersprache_history
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    muttersprache_id INTEGER                             NOT NULL,
    name        TEXT,
    kennzeichen_iso_639_1 TEXT,
    kennzeichen_iso_639_2 TEXT,
    kennzeichen_iso_639_3 TEXT,
    status      smallint  not null,
    created_on        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by        VARCHAR(255),
    changed_on        TIMESTAMP WITHOUT TIME ZONE,
    changed_by        VARCHAR(255),
    action            CHAR,
    action_timestamp  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE
    OR REPLACE FUNCTION muttersprache_audit() RETURNS TRIGGER
    LANGUAGE plpgsql
AS
$$
BEGIN
    IF
        TG_OP = 'DELETE' THEN
        INSERT INTO muttersprache_history (muttersprache_id, name, kennzeichen_iso_639_1, kennzeichen_iso_639_2, kennzeichen_iso_639_3, status, created_on, created_by , changed_on, changed_by, action, action_timestamp)
        VALUES (OLD.id, OLD.name, OLD.kennzeichen_iso_639_1, OLD.kennzeichen_iso_639_2, OLD.kennzeichen_iso_639_3, OLD.status, OLD.created_on, OLD.created_by, OLD.changed_on, OLD.changed_by, 'D', NOW());
        RETURN OLD;
    ELSIF
        TG_OP = 'UPDATE' THEN
        INSERT INTO muttersprache_history (muttersprache_id, name, kennzeichen_iso_639_1, kennzeichen_iso_639_2, kennzeichen_iso_639_3, status, created_on, created_by , changed_on, changed_by, action, action_timestamp)
        VALUES (NEW.id, NEW.name, NEW.kennzeichen_iso_639_1, NEW.kennzeichen_iso_639_2, NEW.kennzeichen_iso_639_3, NEW.status, NEW.created_on, NEW.created_by , NEW.changed_on, NEW.changed_by, 'U', NOW());
        RETURN NEW;
    ELSIF
        TG_OP = 'INSERT' THEN
        INSERT INTO muttersprache_history (muttersprache_id, name, kennzeichen_iso_639_1, kennzeichen_iso_639_2, kennzeichen_iso_639_3, status, created_on, created_by , changed_on, changed_by, action, action_timestamp)
        VALUES (NEW.id, NEW.name, NEW.kennzeichen_iso_639_1, NEW.kennzeichen_iso_639_2, NEW.kennzeichen_iso_639_3, NEW.status, NEW.created_on, NEW.created_by , NEW.changed_on, NEW.changed_by, 'I', NOW());
        RETURN NEW;
    END IF;
    RETURN NULL; -- result is ignored since this is an AFTER trigger
END;
$$;

alter function muttersprache_audit() owner to ibosng;

CREATE TRIGGER muttersprache_insert
    AFTER INSERT
    ON muttersprache
    FOR EACH ROW
EXECUTE FUNCTION muttersprache_audit();

CREATE TRIGGER muttersprache_update
    AFTER UPDATE
    ON muttersprache
    FOR EACH ROW
EXECUTE FUNCTION muttersprache_audit();

CREATE TRIGGER muttersprache_delete
    AFTER DELETE
    ON muttersprache
    FOR EACH ROW
EXECUTE FUNCTION muttersprache_audit();

insert into muttersprache (kennzeichen_iso_639_1, kennzeichen_iso_639_3, kennzeichen_iso_639_2, name, status, created_by)
values  ('bg', 'bul', 'bul', 'Bulgarisch', 1, current_user),
        ('ca', 'cat', 'cat', 'Katalanisch', 1, current_user),
        ('bs', 'bos', 'bos', 'Bosnisch', 1, current_user),
        ('co', 'cos', 'cos', 'Korsisch', 1, current_user),
        ( 'cs', 'cze', 'ces', 'Tschechisch', 1, current_user),
        ('cy', 'wel', 'cym', 'Walisisch', 1, current_user),
        ('da', 'dan', 'dan', 'Dänisch', 1, current_user),
        ('de', 'ger', 'deu', 'Deutsch', 1, current_user),
        ('el', 'gre', 'ell', 'Griechisch ', 1, current_user),
        ('en', 'eng', 'eng', 'Englisch', 1, current_user),
        ('es', 'spa', 'spa', 'Spanisch', 1, current_user),
        ('eu', 'baq', 'eus', 'Baskisch', 1, current_user),
        ('fi', 'fin', 'fin', 'Finnisch', 1, current_user),
        ('fo', 'fao', 'fao', 'Färöisch', 1, current_user),
        ('fr', 'fre', 'fra', 'Französisch', 1, current_user),
        ('ga', 'gle', 'gle', 'Irisch', 1, current_user),
        ('gd', 'gla', 'gla', 'Schottisch-Gälisch', 1, current_user),
        ('hr', 'hrv', 'hrv', 'Kroatisch', 1, current_user),
        ('hi', 'hin', 'hin', 'Hindi', 1, current_user),
        ( 'hu', 'hun', 'hun', 'Ungarisch', 1, current_user),
        ('is', 'ice', 'isl', 'Isländisch', 1, current_user),
        ('it', 'ita', 'ita', 'Italienisch', 1, current_user),
        ('ja', 'jpn', 'jpn', 'Japanisch', 1, current_user),
        ('ka', 'geo', 'kat', 'Georgisch', 1, current_user),
        ( 'lt', 'lit', 'lit', 'Litauisch', 1, current_user),
        ('lv', 'lav', 'lav', 'Lettisch', 1, current_user),
        ( 'mk', 'mac', 'mkd', 'Mazedonisch', 1, current_user),
        ('mt', 'mlt', 'mlt', 'Maltesisch', 1, current_user),
        ( 'nl', 'dut', 'nld', 'Niederländisch', 1, current_user),
        ('no', 'nor', 'nor', 'Norwegisch', 1, current_user),
        ( 'pl', 'pol', 'pol', 'Polisch', 1, current_user),
        ('pt', 'por', 'por', 'Portugiesisch', 1, current_user),
        ('ro', 'rum', 'ron', 'Rumänisch', 1, current_user),
        ('ru', 'rus', 'rus', 'Russisch', 1, current_user),
        ('sc', 'srd', 'srd', 'Sardinisch', 1, current_user),
        ('sk', 'slo', 'slk', 'Slowakisch', 1, current_user),
        ('sl', 'slv', 'slv', 'Slowenisch', 1, current_user),
        ('sq', 'alb', 'sqi', 'Albanisch', 1, current_user),
        ('sr', 'srp', 'srp', 'Serbisch', 1, current_user),
        ('sv', 'swe', 'swe', 'Schwedisch', 1, current_user),
        ( 'tr', 'tur', 'tur', 'Türkisch', 1, current_user),
        ('zh', 'chi', 'zho', 'Chinesisch', 1, current_user),
        ( 'pl', 'pol', 'pol', 'Polnisch', 1, current_user),
        ('ar', 'ara', 'ara', 'Arabisch', 1, current_user),
        ('fa', 'fas', 'fas', 'Persich (Farsi)', 1, current_user),
        ('so', 'som', 'som', 'Somali', 1, current_user),
        ('ps', 'pus', 'pus', 'Paschtu',1, current_user);