CREATE TABLE kompetenz
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teilnehmer_id    INTEGER                             NOT NULL,
    art              VARCHAR(255),
    name             VARCHAR(255),
    confidence_name  DOUBLE PRECISION,
    score            NUMERIC,
    confidence_score DOUBLE PRECISION,
    created_on       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by       VARCHAR(255),
    changed_on       TIMESTAMP WITHOUT TIME ZONE,
    changed_by       VARCHAR(255)
);

CREATE TABLE kompetenz_history
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teilnehmer_id    INTEGER                             NOT NULL,
    kompetenz_id     INTEGER                             NOT NULL,
    art              VARCHAR(255),
    name             VARCHAR(255),
    confidence_name  DOUBLE PRECISION,
    score            NUMERIC,
    confidence_score DOUBLE PRECISION,
    created_on       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by       VARCHAR(255),
    changed_on       TIMESTAMP WITHOUT TIME ZONE,
    changed_by       VARCHAR(255),
    action           CHAR,
    action_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE
    OR REPLACE FUNCTION kompetenz_audit() RETURNS TRIGGER
    LANGUAGE plpgsql
AS
$$
BEGIN
    IF
        TG_OP = 'DELETE' THEN
        INSERT INTO kompetenz_history (kompetenz_id, teilnehmer_id, art, name, confidence_name, score, confidence_score,
                                       created_on,
                                       created_by, changed_on, changed_by, action, action_timestamp)
        VALUES (OLD.id,
                OLD.teilnehmer_id,
                OLD.art,
                OLD.name,
                OLD.confidence_name,
                OLD.score,
                OLD.confidence_score,
                OLD.created_on, OLD.created_by, OLD.changed_on, OLD.changed_by, 'D', NOW());
        RETURN OLD;
    ELSIF
        TG_OP = 'UPDATE' THEN
        INSERT INTO kompetenz_history (kompetenz_id, teilnehmer_id, art, name, confidence_name, score, confidence_score,
                                       created_on,
                                       created_by, changed_on, changed_by, action, action_timestamp)
        VALUES (NEW.id,
                NEW.art,
                NEW.name,
                NEW.confidence_name,
                NEW.score,
                NEW.confidence_score,
                NEW.created_on, NEW.created_by, NEW.changed_on, NEW.changed_by, 'U', NOW());
        RETURN NEW;
    ELSIF
        TG_OP = 'INSERT' THEN
        INSERT INTO kompetenz_history (kompetenz_id, teilnehmer_id, art, name, confidence_name, score, confidence_score, created_on,
                                       created_by, changed_on, changed_by, action, action_timestamp)
        VALUES (NEW.id,
                NEW.teilnehmer_id,
                NEW.art,
                NEW.name,
                NEW.confidence_name,
                NEW.score,
                NEW.confidence_score,
                NEW.created_on, NEW.created_by, NEW.changed_on, NEW.changed_by, 'I', NOW());

        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$;

ALTER FUNCTION kompetenz_audit() OWNER TO ibosng;

CREATE TRIGGER kompetenz_insert
    AFTER INSERT
    ON kompetenz
    FOR EACH ROW
EXECUTE PROCEDURE kompetenz_audit();

CREATE TRIGGER kompetenz_update
    AFTER UPDATE
    ON kompetenz
    FOR EACH ROW
EXECUTE PROCEDURE kompetenz_audit();

CREATE TRIGGER kompetenz_delete
    AFTER DELETE
    ON kompetenz
    FOR EACH ROW
EXECUTE PROCEDURE kompetenz_audit();


