INSERT INTO email_template (identifier, language, subject, body, status, created_by, created_on)
VALUES ('gateway-service.ma-abwesenheit-genehmigt,',
        (SELECT id FROM languages WHERE name = 'german'),
        'Abwesenheit genehmigt',
        'Liebe/r %s,<br><br>Ihr/e Führungskraft hat Ihren Abwesenheitsantrag für den Zeitraum von %s bis %s genehmigt. Du kannst den Antrag hier anschauen. <a href=""%s"">LINK</a>',
        1,
        current_user,
        current_timestamp),

       ('gateway-service.ma-abwesenheit-info',
        (SELECT id FROM languages WHERE name = 'german'),
        'Abwesenheit erstellt, bitte genehmigen. %s',
        'Liebe/r %s,<br><br>Ihr/e KollegIn %s hat soeben einen Abwesenheitsantrag für den Zeitraum von %s bis %s gestellt. Bitte um Prüfung. <a href=""%s"">LINK</a>',
        1,
        current_user,
        current_timestamp),

       ('gateway-service.ma-abwesenheit-storno-info',
        (SELECT id FROM languages WHERE name = 'german'),
        'Abwesenheit wird storniert, bitte genehmigen. %s',
        'Liebe/r %s,<br><br>Ihr/e KollegIn %s möchte eine Abwesenheit für den Zeitraum von %s bis %s stornieren. Du kannst den Stornoantrag hier genehmigen oder ablehnen. <a href=""%s"">LINK</a>',
        1,
        current_user,
        current_timestamp),

       ('gateway-service.ma-abwesenheit-abgelehnt',
        (SELECT id FROM languages WHERE name = 'german'),
        'Abwesenheit abgelehnt',
        'Liebe/r %s,<br><br>Ihr/e Führungskraft hat Ihren Abwesenheitsantrag für den Zeitraum von %s bis %s abgelehnt. Du kannst die Begründung in der Übersichtsliste anschauen. <a href=""%s"">LINK</a>',
        1,
        current_user,
        current_timestamp),

       ('gateway-service.ma-abwesenheit-storno-fehlgeschlagen',
        (SELECT id FROM languages WHERE name = 'german'),
        'Abwesenheit Storno abgelehnt',
        'Liebe/r %s,<br><br>Ihr/e Führungskraft hat Ihren Stornoantrag für den Zeitraum von %s bis %s abgelehnt. Du kannst die Begründung in der Übersichtsliste anschauen. <a href=""%s"">LINK</a>',
        1,
        current_user,
        current_timestamp),

       ('gateway-service.ma-abwesenheit-storno-erfolgreich',
        (SELECT id FROM languages WHERE name = 'german'),
        'Abwesenheit Storno genehmigt',
        'Liebe/r %s,<br><br>Ihr/e Führungskraft hat Ihren Stornoantrag für den Zeitraum von %s bis %s genehmigt. Du kannst den Antrag hier anschauen. <a href=""%s"">LINK</a>',
        1,
        current_user,
        current_timestamp);
