insert into land (land_name, land_code, elda_code, telefonvorwahl, created_by)
values ('Abchasien', null, null, '+7', current_user),
       ('Afghanistan', 'AF', 'AFG', '+93', current_user),
       ('Ägypten', 'EG', 'ET', '+20', current_user),
       ('Albanien', 'AL', 'AL', '+355', current_user),
       ('Algerien', 'DZ', 'DZ', '+213', current_user),
       ('Amerikanisch-Samoa', 'AS', 'AS', '+1684', current_user),
       ('Andorra', 'AD', 'AND', '+376', current_user),
       ('Angola', 'AO', 'ANG', '+244', current_user),
       ('Anguilla', 'AI', 'AI', '+1264', current_user),
       ('Antigua und Barbuda', 'AG', 'ANT', '+1268', current_user),
       ('Äquatorialguinea', 'GQ', 'GQ', '+240', current_user),
       ('Argentinien', 'AR', 'RA', '+54', current_user),
       ('Armenien', 'AM', 'ARM', '+374', current_user),
       ('Aruba', 'AW', 'AW', '+297', current_user),
       ('Ascension', null, null, '+247', current_user),
       ('Aserbaidschan', 'AZ', 'AZ', '+994', current_user),
       ('Äthiopien', 'ET', 'ETH', '+251', current_user),
       ('Australien', 'AU', 'AUS', '+61', current_user),
       ('Bahamas', 'BS', 'BS', '+1242', current_user),
       ('Bahrain', 'BH', 'BRN', '+973', current_user),
       ('Bangladesch', 'BD', 'BD', '+880', current_user),
       ('Barbados', 'BB', 'BDS', '+1246', current_user),
       ('Belarus', 'BY', 'BY', '+375', current_user),
       ('Belgien', 'BE', 'B', '+32', current_user),
       ('Belize', 'BZ', 'BH', '+501', current_user),
       ('Benin', 'BJ', 'DY', '+229', current_user),
       ('Bermuda', 'BM', 'BMU', '+1441', current_user),
       ('Bhutan', 'BT', 'BTN', '+975', current_user),
       ('Bolivien', 'BO', 'BOL', '+591', current_user),
       ('Bonaire, Sint Eustatius und Saba', 'BQ', null, '+599', current_user),
       ('Bosnien & Herzegowina', 'BA', 'BIH', '+387', current_user),
       ('Botswana', 'BW', 'RB', '+267', current_user),
       ('Brasilien', 'BR', 'BR', '+55', current_user),
       ('Brunei', 'BN', 'BRU', '+673', current_user),
       ('Bulgarien', 'BG', 'BG', '+359', current_user),
       ('Burkina Faso', 'BF', 'BF', '+226', current_user),
       ('Burundi', 'BI', 'RU', '+257', current_user),
       ('Chile', 'CL', 'RCH', '+56', current_user),
       ('China', 'CN', 'VRC', '+86', current_user),
       ('Cookinseln', 'CK', 'CK', '+682', current_user),
       ('Costa Rica', 'CR', 'CR', '+506', current_user),
       ('Curaçao', 'CW', null, '+599', current_user),
       ('Dänemark', 'DK', 'DK', '+45', current_user),
       ('Deutschland', 'DE', 'D', '+49', current_user),
       ('Dominica', 'DM', 'WD', '+1767', current_user),
       ('Dominikanische Republik', 'DO', 'DOM', '+1809', current_user),
       ('Dschibuti', 'DJ', 'DJI', '+253', current_user),
       ('Ecuador', 'EC', 'EC', '+593', current_user),
       ('El Salvador', 'SV', 'ES', '+503', current_user),
       ('Elfenbeinküste', null, null, '+225', current_user),
       ('Eritrea', 'ER', 'ER', '+291', current_user),
       ('Estland', 'EE', 'EW', '+372', current_user),
       ('Eswatini', 'SZ', null, '+268', current_user),
       ('Falklandinseln', 'FK', null, 'FLK''+5+', current_user),
       ('Färöer', 'FO', 'FR', '+298', current_user),
       ('Fidschi', 'FJ', 'FJI', '+679', current_user),
       ('Finnland', 'FI', 'FIN', '+358', current_user),
       ('Frankreich', 'FR', 'F', '+33', current_user),
       ('Französisch-Guayana', 'GF', 'GF', '+594', current_user),
       ('Französisch-Polynesien', 'PF', 'PF', '+689', current_user),
       ('Gabun', 'GA', 'GAB', '+241', current_user),
       ('Gambia', 'GM', 'WAG', '+220', current_user),
       ('Georgien (ohne Abchasien)', 'GE', 'GE', '+995', current_user),
       ('Ghana', 'GH', 'GH', '+233', current_user),
       ('Gibraltar', 'GI', 'GBZ', '+350', current_user),
       ('Grenada', 'GD', 'WG', '+1473', current_user),
       ('Griechenland', 'GR', 'GR', '+30', current_user),
       ('Grönland', 'GL', 'GL', '+299', current_user),
       ('Großbritannien', 'GB', 'GB', '+44', current_user),
       ('Guadeloupe', 'GP', 'GLP', '+590', current_user),
       ('Guam', 'GU', 'GU', '+1671', current_user),
       ('Guatemala', 'GT', 'GCA', '+502', current_user),
       ('Guinea', 'GN', 'GN', '+224', current_user),
       ('Guinea-Bissau', 'GW', 'GNB', '+245', current_user),
       ('Guyana', 'GY', 'GUY', '+592', current_user),
       ('Haiti', 'HT', 'RH', '+509', current_user),
       ('Honduras', 'HN', 'HD', '+504', current_user),
       ('Hongkong', 'HK', 'HK', '+85', current_user),
       ('Indien', 'IN', 'IND', '+91', current_user),
       ('Indonesien', 'ID', 'RI', '+62', current_user),
       ('Irak', 'IQ', 'IRQ', '+964', current_user),
       ('Iran', 'IR', 'IR', '+98', current_user),
       ('Irland', 'IE', 'IRL', '+353', current_user),
       ('Island', 'IS', 'IS', '+354', current_user),
       ('Israel', 'IL', 'IL', '+972', current_user),
       ('Italien', 'IT', 'I', '+39', current_user),
       ('Jamaika', 'JM', 'JA', '+1876', current_user),
       ('Japan', 'JP', 'J', '+81', current_user),
       ('Jemen', 'YE', 'Y', '+967', current_user),
       ('Jordanien', 'JO', 'HKJ', '+962', current_user),
       ('Kaimaninseln', 'KY', 'KY', '+1345', current_user),
       ('Kambodscha', 'KH', 'K', '+855', current_user),
       ('Kamerun', 'CM', 'CAM', '+237', current_user),
       ('Kanada', 'CA', 'CDN', '+1', current_user),
       ('Kap Verde', 'CV', 'CV', '+238', current_user),
       ('Kasachstan', 'KZ', 'KZ', '+7', current_user),
       ('Katar', 'QA', 'Q', '+974', current_user),
       ('Kenia', 'KE', 'EAK', '+254', current_user),
       ('Kirgisistan', 'KG', 'KS', '+996', current_user),
       ('Kiribati', 'KI', 'KIR', '+686', current_user),
       ('Kokosinseln', 'CC', 'CC', '+61', current_user),
       ('Kolumbien', 'CO', 'CO', '+57', current_user),
       ('Komoren', 'KM', 'COM', '+269', current_user),
       ('Kongo (Republik)', 'CG', 'RCB', '+242', current_user),
       ('Kongo (Demokratische Republik)', 'CD', 'ZRE', '+243', current_user),
       ('Kosovo', 'XK', null, '+383', current_user),
       ('Kroatien', 'HR', 'HR', '+385', current_user),
       ('Kuba', 'CU', 'C', '+53', current_user),
       ('Kuwait', 'KW', 'KWT', '+965', current_user),
       ('Laos', 'LA', 'LAO', '+856', current_user),
       ('Lesotho', 'LS', 'LS', '+266', current_user),
       ('Lettland', 'LV', 'LV', '+371', current_user),
       ('Libanon', 'LB', 'RL', '+961', current_user),
       ('Liberia', 'LR', 'LB', '+231', current_user),
       ('Libyen', 'LY', 'LAR', '+218', current_user),
       ('Liechtenstein', 'LI', 'FL', '+423', current_user),
       ('Litauen', 'LT', 'LT', '+370', current_user),
       ('Luxemburg', 'LU', 'L', '+352', current_user),
       ('Macau', 'MO', 'MAC', '+853', current_user),
       ('Madagaskar', 'MG', 'RM', '+261', current_user),
       ('Malawi', 'MW', 'MW', '+265', current_user),
       ('Malaysia', 'MY', 'MAL', '+60', current_user),
       ('Malediven', 'MV', 'MV', '+960', current_user),
       ('Mali', 'ML', 'RMM', '+223', current_user),
       ('Malta', 'MT', 'M', '+356', current_user),
       ('Marokko', 'MA', 'MA', '+212', current_user),
       ('Marshallinseln', 'MH', 'MH', '+692', current_user),
       ('Martinique', 'MQ', 'MTQ', '+596', current_user),
       ('Mauretanien', 'MR', 'RIM', '+222', current_user),
       ('Mauritius', 'MU', 'MS', '+230', current_user),
       ('Mayotte', 'YT', 'ME', '+262', current_user),
       ('Mexiko', 'MX', 'MEX', '+52', current_user),
       ('Mikronesien', 'FM', 'FSM', '+691', current_user),
       ('Moldau', 'MD', 'MD', '+373', current_user),
       ('Monaco', 'MC', 'MC', '+377', current_user),
       ('Mongolei', 'MN', 'MNL', '+976', current_user),
       ('Montenegro', 'ME', 'MNE', '+382', current_user),
       ('Montserrat', 'MS', 'MSR', '+1664', current_user),
       ('Mosambik', 'MZ', 'MOC', '+258', current_user),
       ('Myanmar', 'MM', 'BUR', '+95', current_user),
       ('Namibia', 'NA', 'NAM', '+264', current_user),
       ('Nauru', 'NR', 'WAI', '+674', current_user),
       ('Nepal', 'NP', 'NEP', '+977', current_user),
       ('Neukaledonien', 'NC', 'NCL', '+687', current_user),
       ('Neuseeland', 'NZ', 'NZ', '+64', current_user),
       ('Nicaragua', 'NI', 'NIC', '+505', current_user),
       ('Niederlande', 'NL', 'NL', '+31', current_user),
       ('Niger', 'NE', 'RN', '+227', current_user),
       ('Nigeria', 'NG', 'WAN', '+234', current_user),
       ('Niue', 'NU', 'NU', '+683', current_user),
       ('Nordkorea', 'KP', 'PRK', '+850', current_user),
       ('Nordmazedonien', 'MK', 'MK', '+389', current_user),
       ('Norfolkinsel', 'NF', 'NF', '+6723', current_user),
       ('Norwegen', 'NO', 'N', '+47', current_user),
       ('Oman', 'OM', 'OM', '+968', current_user),
       ('Österreich', 'AT', 'A', '+43', current_user),
       ('Osttimor', 'TL', 'TP', '+670', current_user),
       ('Pakistan', 'PK', 'PK', '+92', current_user),
       ('Palästina', 'PS', 'PAL', '+970', current_user),
       ('Palau', 'PW', 'PW', '+680', current_user),
       ('Panama', 'PA', 'PA', '+507', current_user),
       ('Papua-Neuguinea', 'PG', 'PNG', '+675', current_user),
       ('Paraguay', 'PY', 'PY', '+595', current_user),
       ('Peru', 'PE', 'PE', '+51', current_user),
       ('Philippinen', 'PH', 'RP', '+63', current_user),
       ('Pitcairninseln', 'PN', 'PN', '+649', current_user),
       ('Polen', 'PL', 'PL', '+48', current_user),
       ('Portugal', 'PT', 'P', '+351', current_user),
       ('Puerto Rico', 'PR', 'PRI', '+1787', current_user),
       ('Réunion', 'RE', 'RE', '+262', current_user),
       ('Ruanda', 'RW', 'RWA', '+250', current_user),
       ('Rumänien', 'RO', 'RO', '+40', current_user),
       ('Russland', 'RU', 'RUS', '+7', current_user),
       ('Saint-Pierre & Miquelon', null, 'PM', '+508', current_user),
       ('Salomonen', 'SB', 'SLB', '+677', current_user),
       ('Sambia', 'ZM', 'Z', '+260', current_user),
       ('Samoa', 'WS', 'WS', '+685', current_user),
       ('San Marino', 'SM', 'RSM', '+378', current_user),
       ('São Tomé & Príncipe', 'ST', 'STP', '+239', current_user),
       ('Saudi-Arabien', 'SA', 'SA', '+966', current_user),
       ('Schweden', 'SE', 'S', '+46', current_user),
       ('Schweiz', 'CH', 'CH', '+41', current_user),
       ('Senegal', 'SN', 'SN', '+221', current_user),
       ('Serbien', 'RS', 'SRB', '+381', current_user),
       ('Seychellen', 'SC', 'SY', '+248', current_user),
       ('Sierra Leone', 'SL', 'WAL', '+232', current_user),
       ('Simbabwe', 'ZW', 'ZW', '+263', current_user),
       ('Singapur', 'SG', 'SGP', '+65', current_user),
       ('Sint Maarten', 'SX', null, '+1721', current_user),
       ('Slowakei', 'SK', 'SK', '+421', current_user),
       ('Slowenien', 'SI', 'SLO', '+386', current_user),
       ('Somalia', 'SO', 'SO', '+252', current_user),
       ('Spanien', 'ES', 'E', '+34', current_user),
       ('Sri Lanka', 'LK', 'CL', '+94', current_user),
       ('St. Helena', 'SH', 'SH', '+290', current_user),
       ('St. Kitts und Nevis', 'KN', 'KN', '+1869', current_user),
       ('St. Lucia', 'LC', 'WL', '+1758', current_user),
       ('St. Vincent und die Grenadinen', 'VC', 'WV', '+1784', current_user),
       ('Südafrika', 'ZA', 'ZA', '+27', current_user),
       ('Sudan', 'SD', 'SUD', '+249', current_user),
       ('Südsudan', 'SS', 'SS', '+211', current_user),
       ('Südkorea', 'KR', 'ROK', '+82', current_user),
       ('Südossetien', null, null, '+7', current_user),
       ('Suriname', 'SR', 'SME', '+597', current_user),
       ('Syrien', 'SY', 'SYR', '+963', current_user),
       ('Tadschikistan', 'TJ', 'TJ', '+992', current_user),
       ('Taiwan (Republik China)', 'TW', 'TA', '+886', current_user),
       ('Tansania', 'TZ', 'EAT', '+255', current_user),
       ('Thailand', 'TH', 'T', '+66', current_user),
       ('Togo', 'TG', 'TG', '+228', current_user),
       ('Tokelau', 'TK', 'TK', '+690', current_user),
       ('Tonga', 'TO', 'TO', '+676', current_user),
       ('Trinidad und Tobago', 'TT', 'TT', '+1868', current_user),
       ('Tristan da Cunha', null, null, '+290', current_user),
       ('Tschad', 'TD', 'TCH', '+235', current_user),
       ('Tschechien', 'CZ', 'CZ', '+420', current_user),
       ('Tunesien', 'TN', 'TN', '+216', current_user),
       ('Türkei', 'TR', 'TR', '+90', current_user),
       ('Türkische Republik Nordzypern', null, null, '+90', current_user),
       ('Turkmenistan', 'TM', 'TM', '+993', current_user),
       ('Turks- und Caicosinseln', 'TC', 'TC', '+1649', current_user),
       ('Tuvalu', 'TV', 'TUV', '+688', current_user),
       ('Uganda', 'UG', 'EAU', '+256', current_user),
       ('Ukraine', 'UA', 'UA', '+380', current_user),
       ('Ungarn', 'HU', 'H', '+36', current_user),
       ('Uruguay', 'UY', 'ROU', '+598', current_user),
       ('USA', 'US', 'USA', '+1', current_user),
       ('Usbekistan', 'ZU', 'UZ', '+998', current_user),
       ('Vanuatu', 'VU', 'VU', '+678', current_user),
       ('Vatikan', 'VA', 'V', '+379', current_user),
       ('Venezuela', 'VE', 'YV', '+58', current_user),
       ('Vereinigte Arabische Emirate', 'AE', 'UAE', '+971', current_user),
       ('Vereinigtes Königreich', 'US', 'USA', '+44', current_user),
       ('Vietnam', 'VN', 'VN', '+84', current_user),
       ('Wallis und Futuna', 'WF', 'WF', '+681', current_user),
       ('Weihnachtsinsel', 'CX', 'CX', '+61', current_user),
       ('Zentralafrikanische Republik', 'CF', 'RCA', '+236', current_user),
       ('Zypern', 'CY', 'CY', '+357', current_user),
       ('Amerik. Jungferninseln', 'VI', 'VI', '+1-340', current_user),
       ('Antarktis', 'AQ', 'AQ', '672', current_user),
       ('Br. Jungferninseln', 'VG', 'VG', '+1-284', current_user),
       ('Br. Territ./Ind. Ozean', 'IO', 'IO', '+246', current_user),
       ('Marianen (zu USA)', 'MP', 'MNP', '+1-670', current_user),
       ('Niederländische Antillen', 'AN', 'NA', '+599', current_user),
       ('St.Pierre', 'PM', 'PM', '+508', current_user),
       ('Svalbard', 'SJ', 'SJ', '+47', current_user),
       ('Swasiland', 'SZ', 'SD', '+268', current_user);
