INSERT INTO email_template (identifier, language, subject, body, status, created_by, created_on)
VALUES ('gateway-service.vertragsaenderung.people-informiren', (select id from languages where name = 'german'),
        'Vertragsänderung %s bitte prüfen',
        'Liebe KollegInnen, für einen Mitarbeiter wurde eine Vertragsänderung zur Prüfung vorgelegt. Bitte deren Daten im System prüfen. %s',
        1, current_user, current_timestamp),
('gateway-service.vertragsaenderung.people-lehnt-ab', (select id from languages where name = 'german'),
        'Vertragsänderung %s bitte erneut bearbeiten',
        'People hat den Vorgang unvollständig bewertet. Bitte um Vervollständigung der Daten und erneutes Vorliegen zur Prüfung. %s',
        1, current_user, current_timestamp),
('gateway-service.vertragsaenderung.lohnverrechnung-informiren', (select id from languages where name = 'german'),
        'Vertragsänderung %s bitte prüfen',
        'Liebe KollegInnen, für einen Mitarbeiter wurde eine Vertragsänderung zur Prüfung vorgelegt. Bitte deren Daten im System prüfen. %s',
        1, current_user, current_timestamp),
('gateway-service.vertragsaenderung.lohnverrechnung-lenht-ab', (select id from languages where name = 'german'),
        'Vertragsänderung %s bitte erneut prüfen',
        'Lohnverrechnung hat den Vorgang unvollständig bewertet. Bitte um Vervollständigung der Daten und erneutes Vorliegen zur Prüfung.',
        1, current_user, current_timestamp),
('gateway-service.vertragsaenderung.genehmigenden-informiren', (select id from languages where name = 'german'),
        'Vertragsänderung %s bitte genehmigen',
        'Liebe KollegInnen, für einen Mitarbeiter wurde eine Vertragsänderung zur Genehmigung vorgelegt. Bitte den Zusatz im System bewerten. %s',
        1, current_user, current_timestamp),
('gateway-service.vertragsaenderung.genehmigenden-lenht-ab', (select id from languages where name = 'german'),
        'Vertragsänderung %s bitte erneut prüfen',
        'Der Genehmiger hat den Vorgang unvollständig bewertet. Bitte um Vervollständigung der Daten und erneutes Vorliegen zur Prüfung. ',
        1, current_user, current_timestamp);