package com.ibosng.dbservice.entities.reports;

import lombok.Getter;

@Getter
public enum ReportType {

    MANUAL("manual"),
    SCHRIFTVERKEHR("schriftverkehr"),
    AUTOGENERATED("autogenerated"),
    NOT_MANUAL("notManual");

    private final String value;

    public static ReportType fromValue(String value) {
        for (ReportType source : ReportType.values()) {
            if (source.getValue().equals(value)) {
                return source;
            }
        }
        throw new IllegalArgumentException("Unknown enum value: " + value);
    }

    ReportType(String value) {
        this.value = value;
    }
}
